### ISSUE TITLE
This action does not work between different releases 

### ISSUE THREAD

**Issue by antoniogamizbadger** [dorny/paths-filter#101]
Hi, I have a workflow that it's triggered only by the `release` event. The problem is that it does not detect any file changes inside that release.

This is the workflow:

~~~
name: Deploy

on:
  release:
    types: [ released ]

env:
  PROD_IMAGE_PATH: ghcr.io/badgermaps/badger-docrouter:prod
  DEV_IMAGE_PATH: ghcr.io/badgermaps/badger-docrouter:dev

jobs:
  needs-rebuild:
      runs-on: ubuntu-latest
      outputs:
        changed: ${{ steps.needs-rebuild.outputs.files }}
      steps:
        - uses: actions/checkout@v2
        - uses: dorny/paths-filter@v2
          id: needs-rebuild
          with:
            filters: |
              files:
                - 'Dockerfile'
                - 'requirements.txt'
                - 'package.json'
~~~

If the release contains changes on `Dockerfile`, they are not detected.

**Comment by rigoneri** [comment]
@dorny I have a similar issue. Is it possible for me to configure it to compare against the previous release? Is there an example  of that? Basically what I want to do is just run the action/release if certain files changes. 
Thank you

**Comment by rigoneri** [comment]
I was able to get it to work by doing something like this during a release:

```
    - name: Getting sha for last release
      id: last-release
      shell: bash
      run: |
        tag=`gh release list | sed -n '2 p' | awk '{print $(NF -1);}'`
        echo "Tag: $tag"
        sha=`git show-ref --tags | grep $tag | awk '{print $1;}'`
        echo "SHA: $sha"
        echo "::set-output name=sha::$sha"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
  
    - name: Checking changes
      uses: dorny/paths-filter@v2
      id: changes
      with:
        base: ${{ steps.last-release.outputs.sha }}
        filters:
```

Could this be somehow built into paths-filter?
