### ISSUE TITLE
[Question] filter on PR closed

### ISSUE THREAD

**Issue by claywd-x** [dorny/paths-filter#103]
So, This is working great for making sure a specific workflow runs for files changed in a specific path when the PR is open and pushes are being made. However, I'd like to use it to compare files changed in the path when the pr is closed. The problem is that I immediately get this error and I'm not sure how to get around it. 
<img width="648" alt="Screen Shot 2021-09-08 at 10 35 02 AM" src="https://user-images.githubusercontent.com/81392154/132540013-97f3d86a-0618-449a-8d03-39221f3ecf58.png">
  
```
name: 'PR Closed Workflow'

on:
  pull_request:
    types:
      - closed

jobs:
  # run only if some file in 'src' folder was changed
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          src:
            - 'some_path/**'
  new_job:
      name: 'some_job'
      runs-on: ubuntu-latest
      needs: changes
      if: ${{ needs.changes.outputs.src == 'true' }}
      defaults:
        run:
          shell: bash
          working-directory: some_path
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: do things
         run: echo "did a thing"
```
