### ISSUE TITLE
API rate limit exceeded - is this action doing too much?

### ISSUE THREAD

**Issue by teebu** [dorny/paths-filter#108]
We have a mono repo and we use this action to see if we need to run specific tasks for each project. 

This hasn't been a problem before, but we have a lot of actions now that use this to detect changes. Is this action too API request-heavy?

```
Fetching list of changed files for PR#1063 from Github API
  Invoking listFiles(pull_number: 1063, page: 1, per_page: 100)
  ::endgroup::
Error: API rate limit exceeded for installation ID 16004555.
```

Using:
```
      - uses: actions/checkout@v2
        with:
          # This may save additional git fetch round trip if merge-base is found within latest 20 commits
          fetch-depth: 20
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            should_include:
              - 'Project1/**'
```

I can't figure out which limit is this action is consuming. 
https://docs.github.com/en/rest/reference/rate-limit

``` 
client.pulls.listFiles
```
Would this be considered core or subject to [1,000 req/sec](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting) limit?
