### ISSUE TITLE
Why is outputs []?

### ISSUE THREAD

**Issue by BjarkeMeier** [dorny/paths-filter#109]
[Here is an example](https://github.com/Energinet-DataHub/geh-charges/pull/701/checks?check_run_id=3869407972) where the `outputs` appears to be an empty array. I expected it to be an object with a `functionhost` property with value `false` as there are no changes to any file in the filter.

![image](https://user-images.githubusercontent.com/11583438/136949871-dc9201f5-176e-4ca1-bc1a-2a8caf59770f.png)

Screendump of [the workflow](https://github.com/Energinet-DataHub/geh-charges/pull/701/files):
![image](https://user-images.githubusercontent.com/11583438/136950088-d5f6cc9a-dbb0-4f04-9020-46210b36ff46.png)

So the guard in line 60 apparently doesn't work as expected. Am I missing something?

**Comment by airtonix** [comment]
Experiencing this too: 

![image](https://user-images.githubusercontent.com/61225/187571934-5622eacb-cbef-4bc0-a169-0d55d3c80bb6.png)

```
name: Mainline

# Mainline Workflow
#
# Intention:
#  - process changesets (CHANGELOG and version calculations)
#  - deploy App Storybook (if needed)
#  - deploy Balance Website (if needed)
#  - deploy Apps (if needed)
#  - update computed workflows based on repo state

'on':
  push:
    branches:
      - master
      - test/master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  NODE_OPTIONS: --max-old-space-size=8096


jobs:
  Changes:
    runs-on: ubuntu-latest

    outputs:
      changes: ${{ steps.filter.outputs.changes }}
      Apps: ${{ steps.filter.outputs.Apps }}
      AppStorybook: ${{ steps.filter.outputs.AppStorybook }}
      Changesets: ${{ steps.filter.outputs.Changesets }}
      Balance: ${{ steps.filter.outputs.Balance }}
      Infrastructure: ${{ steps.filter.outputs.Infrastructure }}

    steps:
      #
      # Not on a Pull Request, so dorny/paths-filter needs a checkout
      #
      - uses: actions/checkout@v3
        with:
          # This may save additional git fetch roundtrip
          fetch-depth: 0

      - run: git fetch origin master:master
        if: github.ref_name != 'master'

      #
      # Build a list of namespace change flags
      #
      - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721
        id: filter
        with:
          ref: HEAD^1
          filters: |
            Changesets:
              - added: '.changesets/!(README)*.md'

            Apps:
              - 'apps/!(*storybook)**/*'

            AppStorybook:
              - 'apps/**'
              - 'apps/storybook/**'

            Balance:
              - 'design-system/**'

            Infrastructure:
              - 'infrastructure/**'

      - run: node -e 'console.log(${{toJson(steps.filter.outputs)}})'

  Changesets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    needs: Changes
    if: needs.Changes.outputs.Changesets == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          # this sets up the git connection string for the pull
          # and any further pushes. Important, because this particular
          # step requires a token with certain scopes to modify items in the
          # .github/workflows directory.
          token: ${{secrets.RECKON_BOT_TOKEN}}

      - name: Provision
        uses: ./packages/tools/action-setup-tooling
        with:
          SetupCommand: ./setup.bash

      - name: Install Deps
        uses: ./packages/tools/action-setup-pnpm

      - name: Set Reckonbot as Author
        uses: ./packages/tools/action-setup-repobot
        with:
          Email: ${{secrets.RECKON_BOT_GIT_EMAIL}}
          Name: ${{secrets.RECKON_BOT_GIT_NAME}}

      #
      # Process Changesets
      #
      # If the pushed ref is a branch and that branch name is 'master',
      # and the commit message doesnt look like it was created by processing changesets
      # then lets try processing any changsets.
      - name: Process changesets
        uses: ./packages/tools/action-process-changesets

```

**Comment by airtonix** [comment]
![image](https://user-images.githubusercontent.com/61225/187572437-8a858a3d-72d1-4a08-9202-45d7363d533a.png)

![image](https://user-images.githubusercontent.com/61225/187572519-40a91caf-4052-43e0-8ab4-40227bf3164c.png)

Since our filters look like: 

```yml

      - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721
        id: filter
        with:
          ref: master
          filters: |
            Changesets:
              - added: '.changesets/!(README)*.md'

            Apps:
              - 'apps/!(*storybook)**/*'

            AppStorybook:
              - 'apps/**'
              - 'apps/storybook/**'

            Balance:
              - 'design-system/**'

            Infrastructure:
              - 'infrastructure/**'
```

I'd expect that our `needs.Changes.outputs.Changesets == 'true'`

but : 

![image](https://user-images.githubusercontent.com/61225/187572703-0ec05d51-aacc-4987-80ee-2f433a18a751.png)



---

```yml
name: Mainline

# Mainline Workflow
#
# Intention:
#  - process changesets (CHANGELOG and version calculations)
#  - deploy App Storybook (if needed)
#  - deploy Balance Website (if needed)
#  - deploy Apps (if needed)
#  - update computed workflows based on repo state

'on':
  push:
    branches:
      - master
      - test/master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  NODE_OPTIONS: --max-old-space-size=8096

jobs:
  Changes:
    runs-on: ubuntu-latest

    outputs:
      changes: ${{ steps.filter.outputs.changes }}
      Apps: ${{ steps.filter.outputs.Apps }}
      AppStorybook: ${{ steps.filter.outputs.AppStorybook }}
      Changesets: ${{ steps.filter.outputs.Changesets }}
      Balance: ${{ steps.filter.outputs.Balance }}
      Infrastructure: ${{ steps.filter.outputs.Infrastructure }}

    steps:
      #
      # Not on a Pull Request, so dorny/paths-filter needs a checkout
      #
      - uses: actions/checkout@v3
        with:
          # This may save additional git fetch roundtrip
          fetch-depth: 0

      - run: git fetch origin master:master
        if: github.ref_name != 'master'

      #
      # Build a list of namespace change flags
      #
      - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721
        id: filter
        with:
          ref: master
          filters: |
            Changesets:
              - added: '.changesets/!(README)*.md'

            Apps:
              - 'apps/!(*storybook)**/*'

            AppStorybook:
              - 'apps/**'
              - 'apps/storybook/**'

            Balance:
              - 'design-system/**'

            Infrastructure:
              - 'infrastructure/**'

      - run: node -e 'console.log(${{toJson(steps.filter.outputs)}})'

  Changesets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    needs: Changes
    if: needs.Changes.outputs.Changesets == 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          # this sets up the git connection string for the pull
          # and any further pushes. Important, because this particular
          # step requires a token with certain scopes to modify items in the
          # .github/workflows directory.
          token: ${{secrets.RECKON_BOT_TOKEN}}

      - name: Provision
        uses: ./packages/tools/action-setup-tooling
        with:
          SetupCommand: ./setup.bash

      - name: Install Deps
        uses: ./packages/tools/action-setup-pnpm

      - name: Set Reckonbot as Author
        uses: ./packages/tools/action-setup-repobot
        with:
          Email: ${{secrets.RECKON_BOT_GIT_EMAIL}}
          Name: ${{secrets.RECKON_BOT_GIT_NAME}}

      #
      # Process Changesets
      #
      # If the pushed ref is a branch and that branch name is 'master',
      # and the commit message doesnt look like it was created by processing changesets
      # then lets try processing any changsets.
      - name: Process changesets
        uses: ./packages/tools/action-process-changesets
```
