### ISSUE TITLE
Bug: working-directory makes filters incorrect

### ISSUE THREAD

**Issue by sidvishnoi** [dorny/paths-filter#112]
The expectation was that all the filters are relative to the specified `working-directory`, but it's not the case.

Doesn't work:
```yaml
working-directory: 'functions'
filters: |
  fn:
    - '${{ matrix.dir }}/**'
```

Works:
```yaml
filters: |
  fn:
    - 'functions/${{ matrix.dir }}/**'
```
