### ISSUE TITLE
`list-files` can't be used when using a filter file

### ISSUE THREAD

**Issue by scowalt** [dorny/paths-filter#114]
If you set up a `filters.yaml` file and and use it with `list-files: shell`
```yml
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: .github/filters.yaml
```

Then later on, the list of files won't be output. So, for example, `steps.changed-files.outputs.typescript_source_files` will be an empty string, instead of containing the list of changed files.
