### ISSUE TITLE
Using filter output in jobs `if` does not make a difference

### ISSUE THREAD

**Issue by ivankovnatsky** [dorny/paths-filter#119]
Thanks for your time working on this project!

Goal: Do not run the job if the files under `infrastructure/` changed.

While somehow it does not work in jobs `if`, it does outputs the value in the further commands.

I'm not sure if this is GitHub's issue or the action itself.

I've followed this example here: https://github.com/dorny/paths-filter#conditional-execution

"Execute job in a workflow only if some file in a subfolder is changed"

```yaml
  filter-check:
    container: alpine/git:v2.32.0
    outputs:
      infra: "${{ steps.filter.outputs.infra }}"
    steps:
      - id: filter
        uses: "dorny/paths-filter@v2"
        with:
          filters: |
            infra:
              - 'infrastructure/**'

  dhall-check:
    container: dhallhaskell/dhall:1.40.2
    needs:
      - filter-check
    if: "${{ needs.filter-check.outputs.infra }} == 'false'"
    steps:
      - name: Checkout repository
        uses: "actions/checkout@v2"
        with:
          fetch-depth: '30'
          token: "${{ secrets.SECRET_TOKEN }}"
      - uses: "dhall-lang/setup-dhall@v4"
      - run: dhall version
      - name: Generate ci.yml
        run: make -C ci generate
      - name: Output show
        run: "echo ${{ needs.filter-check.outputs.infra }}"
      - name: Make sure that ci.yml is synchronized with its Dhall source
        run: git diff --exit-code ci/
```

![image](https://user-images.githubusercontent.com/75213/150497180-491baab3-23fe-4978-a1cf-487ff4aa2506.png)
