### ISSUE TITLE
Use recursive rules

### ISSUE THREAD

**Issue by Shatur95** [dorny/paths-filter#12]
Thank you a lot for this action!
Could you add the ability to use rules recursively?
For example:

```yml
- name: Detect changes
  uses: dorny/paths-filter@v2.0.0
  id: changes
  with:
    filters: |
      all:
        - '.github/workflows/main.yml'
        - 'CMakeLists.txt'
        - 'CMake/**'
      utils:
        - ${{ steps.changes.filters.all }}
        - 'Utils/**'
```

Such rule would allow to avoid always check for `all` rule in every step. This is just a simple example. But such feature can help to avoid duplicated paths in dependent filters (very usefull for project with complex dependencies).
