### ISSUE TITLE
Failure on push, but works on pull request

### ISSUE THREAD

**Issue by euqen** [dorny/paths-filter#122]
Hi guys. I'm trying to setup my workflow. Here is example of job which runs on pull request:

```
  can-publish-apispec:
    if: github.event_name == 'pull_request'
    runs-on: self-hosted
    container: node:14.17-alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            apispec:
              - "**/apispec.json"

      - name: Prepare dependencies
        if: steps.changes.outputs.apispec == 'true'
        run: |
            ....
```

It works absolutely fine, but if I run this on push:

```
  publish-apispec:
    runs-on: self-hosted
    container: node:14.17-alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            apispec:
              - "**/apispec.json"       

      - name: Prepare dependencies
        if: steps.changes.outputs.apispec == 'true'
        run: |
              ....
```

It fails with the error: `Error: Unable to locate executable file: git. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.`

I've checked other issues, author suggested to use checkout@v2 before using paths-filter on push events. This is what I actually do, but it still does not work for me. Can someone help please?

**Comment by euqen** [comment]
okay, I found the reason of that. It looks like it's related to https://github.com/actions/checkout/issues/335 when you use custom container image. In this case there is an issue with checkout action, which does not pull .git folder. Workaround was to update git, so final action will look like that:

```
  publish-apispec:
    runs-on: self-hosted
    container: node:14.17-alpine
    steps:
      - name: Install git
        run: |
          apk add git

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            apispec:
              - "**/apispec.json"       

      - name: Prepare dependencies
        if: steps.changes.outputs.apispec == 'true'
        run: |
              ....
```
