### ISSUE TITLE
What permissions does the GitHub Action need?

### ISSUE THREAD

**Issue by arjundashrath** [dorny/paths-filter#123]
This repo has the GitHub Action that uses the GitHub token. Can you please tell me what [permissions](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/) are used for this token? If the permissions are only used in certain conditions, e.g. when a certain input is specified, please share that info as well.

At https://github.com/step-security/secure-workflows we are building a knowledge-base (KB) of permissions needed by different GitHub Actions. When developers try to remediate [ossf/Scorecards](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions) checks, they use the knowledge-base to secure their GitHub Workflows.

Here is an example of how we store KB for an Action:
```
name: "GH Release"
github-token:
  action-input:
    input: github_token
    is-default: true
  permissions:
    contents: write
    contents-reason: to create GitHub release #Reference: https://github.com/softprops/action-gh-release/blob/fe9a9bd3295828558c7a3c004f23f3bf77d155b2/README.md?plain=1#L70 
```
Related Issue:
https://github.com/step-security/secure-workflows/issues/276
