### ISSUE TITLE
Release on push to master

### ISSUE THREAD

**Issue by weilinzung** [dorny/paths-filter#124]
Hi,

We have a default branch "develop".  And when changes push to master, the filter doesn't work properly on the Release workflow.

For example, we changed a file from the backend folder. 

```
Results:
Filter frontend = false
Filter backend = false
```

```
name: Release
on:
  push:
    branches:
      - master

...

    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend: 
                      - xxxx
            backend:
                      - xxxx

```

--- 

However, the Staging workflow is working fine.

Results:
Filter frontend = false
Filter backend = true

```
name: Staging
on:
  push:
    branches:
      - develop


...

    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend: 
                      - xxxx
            backend:
                      - xxxx
```

Is something about the base branch and with checkout action?
