### ISSUE TITLE
add possibility to overwrite filter output

### ISSUE THREAD

**Issue by Fuzzyma** [dorny/paths-filter#128]
Sometimes I want to run my code no matter what the filter returns. Atm I have to write this for every step:

```
if: steps.changes.outputs.filter1 == 'true' || someOverwriteCondition == 'true'
```

That is very cumbersome. It would be cool to have a parameter `overwrite` to set all filters to true:

```
with:
  filters:
    ...
  overwrite: ${{ someOverwriteCondition }}
```
