### ISSUE TITLE
Trigger flow based on release tag

### ISSUE THREAD

**Issue by sharmmoh1983** [dorny/paths-filter#130]
We are trying to trigger filter based on release tag but it is not happening . Do you have a working sample . I saw similar issue posted but I was looking for specific example

```
on:
  push:
    tags:
       - 'prod-v[0-9]+.[0-9]+.[0-9]+'

 - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: main
```
