### ISSUE TITLE
Ability to filter out shared yaml anchors from `changes` output?

### ISSUE THREAD

**Issue by machty** [dorny/paths-filter#131]
YAML anchors are great for shared config, but if you're trying to use the `changes` output to drive the matrix of another job, then any anchors you use (which are required by YAML to be attached to a YAML object declaration) are themselves going to appear in the list of `changes`, e.g.

```
          shared: &shared
            - common/**
            - config/**
          src:
            - *shared
            - src/**
          lib:
            - *shared
            - lib/**
```

Assuming I only want matrix jobs for `src` and `lib`, this will produced the undesired result of also adding `shared` to the changes array, which will generate a job for `shared` even though `shared` is only meant to be used as a yaml mixin. Is there any way to filter this out?

**Comment by machty** [comment]
@lucasyarid I ended up passing the output to a JS script to filter out undesired output.

**Comment by JavierMonton** [comment]
Having the same issue here. This is a workaround using `bash` and `jq`.

```yaml
  changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter_shared.outputs.without-shared }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            shared: &shared
              - 'data/scala/prism/buildSrc/**'
              - 'data/scala/prism/lib/**'
              - 'deploy/helm/ef-studio-service/**'
              - 'data/scala/prism/Dockerfile'
              - 'deploy/Dockerfile'
            service1:
              - *shared
              - 'foo/bar/**'
            service2:
              - *shared
              - 'baz/**'
      # filter out "shared" from services
      - name: Filter shared
        id: filter_shared
        run: |
          echo "without-shared=$(echo '${{ steps.filter.outputs.changes }}' | jq -c 'map(select(. != "shared"))')" >> $GITHUB_OUTPUT
```
