### ISSUE TITLE
Filter files for a PR based on changes since the last commit

### ISSUE THREAD

**Issue by lleewwiiss** [dorny/paths-filter#136]
I have been using the package to run specific actions based on changes against the base branch, but to avoid the actions running every single push I was wondering if it was possible to run only based on the previous commit for a PR.

Example workflow:
- New PR is created
- Changes detected against base branch run actions
- Push new commit
- No changes detected since the last commit for specific filter skip steps as normal with the if condition

I've tried adding but it seems to get ignored:
```
base: '${{ github.event.pull_request.head.sha }}'
ref: '${{ github.event.pull_request.head.sha }}'
```  

Is this functionality possible or for pull requests it can only work based on changes against the base branch?

**Comment by basickarl** [comment]
Exactly what we are looking for!

**Comment by Superskyyy** [comment]
Really need this, but seems the added PR is not merged for a long time.

**Comment by ChipWolf** [comment]
Also need this

**Comment by pragmaticivan** [comment]
Is anyone working on that feature?

**Comment by Superskyyy** [comment]
> Is anyone working on that feature?

I think it's implemented in the https://github.com/dorny/paths-filter/pull/151, but it's not reviewed.

**Comment by pragmaticivan** [comment]
Because the issue is pretty old, I ended up using another action. Might move back if that gets fixed.

```yml
 - name: Get all changed tf file(s) or deploy workflow changes
    id: changes
    uses: tj-actions/changed-files@v35
    with:
      since_last_remote_commit: "true"
      files: |
        _files_
```
