### ISSUE TITLE
Token usage

### ISSUE THREAD

**Issue by Shatur95** [dorny/paths-filter#14]
I have a question :)
If I understand correctly, specifying token will speedup diff calculation. I tried to use `${{ secrets.GITHUB_TOKEN }}` but it looks like the action continues fetching last commit. Here is how I use it:
```yml
    - name: Detect changes
      uses: dorny/paths-filter@v2.1.0
      id: changes
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filters: |
          all: &all
            - .github/workflows/main.yml
            - CMakeLists.txt
            - CMake/**
...
```
Am I doing something wrong?

**Comment by dorny** [comment]
How is the workflow triggered?

Token can be used to fetch (already calculated) list of changed files from Github API.
But It works only for the pull requests. If the workflow is triggered by other event (e.g. push) Github API doesn't provide any way to get this information and we have to get it using `git diff`.

Another thing is it shouldn't be needed to manually provide the token.
It's already provided as a default value In the [action.yml](https://github.com/dorny/paths-filter/blob/master/action.yml):
```
inputs:
  token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
```
You could opt-out of it by setting it to null.
Honestly I was surprised to find out it works that way.
Only if it behaves differently for me as the owner of both action and the repository which is using it.
