### ISSUE TITLE
outputs object for job is empty but the action itself shows it detected changes?

### ISSUE THREAD

**Issue by sebastiangug** [dorny/paths-filter#144]
Action:
```
jobs:
  filter:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        name: detect changes
        id: filter
        with:
          filters: |
            websocket-server:
              - 'apps/websocket-server/**'
              - 'packages/tracer/**'
              - '.github/workflows/**'
  log:
    needs: [filter]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ needs.filter.outputs.websocket-server }}

  deploy-websocket-server:
    needs: [filter]
    if: needs.filter.outputs.websocket-server == 'true'
```

![image](https://user-images.githubusercontent.com/27768313/180463186-a4f05f32-05ff-4e28-8335-3ace552d7cd0.png)
![image](https://user-images.githubusercontent.com/27768313/180463223-0c7cdd5d-185f-432c-bf12-c50190a28c94.png)
