### ISSUE TITLE
`.github/workflows/**` always evaluates as true

### ISSUE THREAD

**Issue by aubelsb2** [dorny/paths-filter#146]
```
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'src/**'
              - '*.json'
              - '*.js'
              - .github/workflows/**
```

Always evaluates as true log shows that it indicates that every workflow has been modified.
