### ISSUE TITLE
How to generate filters list?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [dorny/paths-filter#148]
```
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            gateway: apps/gateway/src/**
            microservice-1: apps/microservice-1/src/**
            microservice-2: apps/microservice-2/src/**
            ...
            microservice-20: apps/microservice-20/src/**
            
  build-and-push-image:
    needs: changes
    if: ${{ needs.changes.outputs.apps != '[]' && needs.changes.outputs.apps != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJSON(needs.changes.outputs.apps) }}
```

Let's say I have 20 services, is there anyway generate this filter map? 

I want all direct folders under `/apps` push to `steps.filter.outputs.changes` if changed
