### ISSUE TITLE
outputs

### ISSUE THREAD

**Issue by Arvindh-Mojo** [dorny/paths-filter#149]
What is the best way to get the filename as output ? I'm using something like this. I need to get the output of the filename to add it to the comment. 

```
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: criticalfiles.yaml
```

```
      - name: Comment PR
        if : steps.filter.outputs.critical_files == 'true'
```

```
critical_files:
  - "**/test1.go"
  - "**/test2.go"
```
