### ISSUE TITLE
How to dynamically indenify subfolder names who had files changed

### ISSUE THREAD

**Issue by jpsweeney94** [dorny/paths-filter#150]
I have the following action that works to identify when any files have changes in the root `/hak` sub folder and any of the sub folders with in it:
```
name: Discord hak update

on: 
  push:
    branches: master
  
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      hak: ${{ steps.filter.outputs.hak }}
    steps:
      - uses: actions/checkout@v3
      
      - uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            hak:
              - 'hak/**'
```

I then use it to send a message to discord. My question is, how i can identify the individual folder(s) that had files changed dynamically, so i can output that as well?

E..g. given the following file structure and changes: 

```
hak
  - subfolder1
    - File changed
    - Another file changed
  - subfolder2
  - subfolder3
    - File changed
```

How can i identify that `subfolder1` and `subfolder3` had changed files? Ideally I'd like this to be dynamic instead of hard coding the folders in the action job, because folders could be added or deleted in the future. 

Thanks!

**Comment by amirbtb** [comment]
After giving a look at the `changes-test` step of the `test-inline` job in the [.github/workflows/pull-request-verification.yml](https://github.com/dorny/paths-filter/blob/master/.github/workflows/pull-request-verification.yml) pipeline. I can see the `change` output isn't tested in a matrix. Maybe there is an unidentified issue with the `change` output when it used across jobs.

**Comment by amirbtb** [comment]
My bad I forgot the `needs` key in the second job. Here is my workflow file after correction :

```
name: demo_CD

on:
  pull_request: 
    types:
      - closed

jobs:
  changes:
    name: Check files for changes
    runs-on: ubuntu-latest
    outputs:
      folder1: ${{ steps.filter.outputs.folder1 }}
      folder2: ${{ steps.filter.outputs.folder2 }}
      folder3: ${{ steps.filter.outputs.folder3 }}
      folder4: ${{ steps.filter.outputs.folder4 }}
      all_folders: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            folder1:
              - 'src/folder1/**'
            folder2:
              - 'src/folder2/**'
            folder3:
              - 'src/folder3/**'
            folder4:
              - 'src/folder4/**'
  deploy:
    runs-on: ubuntu-latest
    needs: changes
    steps:
    - uses: 'actions/checkout@v2'
       strategy:
         matrix:
           folder: ${{ fromJSON(needs.changes.outputs.all_folders) }}
    - name: 'run tests'
      run: |
        echo: cd ${{ matrix.folder }} && ./run_tests.sh
```

It runs fine  👍🏽  ! Hope it could help 💪🏽
