### ISSUE TITLE
HOWTO: advanced filters check for file rename only

### ISSUE THREAD

**Issue by iamtodor-fb** [dorny/paths-filter#152]
Hello,

I find the following options https://github.com/dorny/paths-filter/blob/master/README.md?plain=1#L446
I was able to configure not to run linter on deleted python files by having the filter
```
with:
          list-files: 'shell'
          filters: |
            py_scripts_filter:
              - added|modified: '**/*.py'
```
But it does not work on renamed files: `R: renaming of a file`: https://git-scm.com/docs/git-diff/2.12.5.

Let's say you have a `foo.py`, you renamed it to `bar.py`, and you did not modify the file's content but the linter still runs against it.

Is it possible to configure the linter not to run on this kind of change?
