### ISSUE TITLE
[FR] Regex capture groups in filters

### ISSUE THREAD

**Issue by ChipWolf** [dorny/paths-filter#153]
It'd be useful to define a regex substitution, for example to capture all top-level directories:

Instead of:
```yaml
with:
  filters: |
    foo:
      - 'foo/**'
    bar:
      - 'bar/**'
    baz:
      - 'baz/**'
```

This would achieve the same thing, with less maintenance:
```yaml
with:
  regex: true
  filters: |
    $1:
      - '([^\/]*)\/.*'
```
