### ISSUE TITLE
Warning when workflow is triggered manually

### ISSUE THREAD

**Issue by arogic** [dorny/paths-filter#158]
Hi,

I am wondering how I can fix the below warning when I trigger the workflow manually?

`
Warning: 'before' field is missing in event payload - changes will be detected from last commit
`

Thanks in advance

**Comment by arogic** [comment]
it seems that if add "base" and set it to "HEAD" it fixes the warning - see below:

```
- uses: dorny/paths-filter@v2.10.2
   id: filter
   with:
     base: HEAD
     filters: |
        ...
```
