### ISSUE TITLE
No changed files are being detected

### ISSUE THREAD

**Issue by xcskier56** [dorny/paths-filter#173]
Hi, I'm really excited about this gem b/c we've been using a home-rolled solution that isn't great. However, I cannot for the life of me get this to recognize that any files have changed. 

This workflow is being run when a PR is is opened or a new commit is added to the PR. I have tried
1. Adding permissions to the workflow per the docs
2. Adding a base branch even though the docs seem to say that this is ignored for PR workflows
3. Globbing everything `"*"`
4. The "Workflow Permissions" are set to "Read and write" in settings

What am I doing wrong? Thanks

Here is my workflow file
```yaml
---
  name: workflow
  
  on:
    push:
      branches: [master]
    pull_request:
      branches: [master]
  
  jobs:
    rspec:
      name: Rspec - Vessel Platform
      runs-on: ubuntu-latest
      # shared env variables
      env:
        BUNDLE_PATH: vendor/bundle
        ImageOS: ubuntu20 # shouldn't need; trying to work around ruby setup bug
        RAILS_DB_HOST: localhost # This is the host that Rails uses to connect to PG
        RAILS_DB_USER: postgres
        RAILS_DB_PWD: WindyPiglet
        RAILS_DB_NAME: name
        PGHOST: localhost # This is the host that Rails uses to connect to PG
        PGDATABASE: postgres # matches POSTGRES_DB
        PGPASSWORD: WindyPiglet # matches POSTGRES_PASSWORD
        PGUSER: postgres # matches POSTGRES_USER
        # And, of course
        RAILS_ENV: test
  
      steps:
        - uses: actions/checkout@v3
        - uses: dorny/paths-filter@v2
          id: changed_files
          with:
            base: master # trying even though docs say it will be ignored
            list-files: json
            filters: |
              src:
                - './engines/vp_survey/**'
                - './engines/vp_authn/**'
                - './applications/platform/**'
              app:
                - 'applications/**'
              github:
                - .github/workflows/**
              app2:
                - applications/**
              all:
                - '*'
  
        - name: Test Changed Files
          run: >-
            echo "Did things change?"
            echo "src: ${{ steps.changed_files.outputs.src }}"
            echo "app: ${{ steps.changed_files.outputs.app }}"
            echo "github: ${{ steps.changed_files.outputs.github }}"
            echo "github changed: ${{ steps.changed_files.outputs.github_files }}"
            echo "app2: ${{ steps.changed_files.outputs.app2 }}"
            echo "all files: ${{ steps.changed_files.outputs.all_files }}"
            echo "changes $${{toJSON(steps.changed_files.outputs.changes)}}"
            echo "files ${{ steps.changed_files.outputs.changed_files }}"
```

And here is the output of the final step
![Screen Shot 2022-11-15 at 4 58 55 PM](https://user-images.githubusercontent.com/2357871/202042574-8a4d4989-a0d8-4b94-a0d8-2e54c8441c3f.png)
