### ISSUE TITLE
Warning: Please update the following actions to use Node.js 16

### ISSUE THREAD

**Issue by iamtodor** [dorny/paths-filter#174]
This is the warning I see every time I my workflow:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: getsentry/paths-filter@v2
```

**Comment by dorny** [comment]
@iamtodor You are probably using an old version of this action. This issue was already addressed in the last two releases. Please verify if you are using either `v2.11.1` or `v2` version tags.

**Comment by maverick1872** [comment]
I can confirm that I'm using the `v2` tag and I'm also seeing this deprecation notice.

**Comment by iamtodor** [comment]
@dorny @maverick1872 
sorry for the late reply - I just got back from vacation. What is the proper way to verify the version? 

Here is my configuration:
```yaml
- name: Check for python file changes
  uses: getsentry/paths-filter@v2
  id: filter
  with:
    list-files: 'shell'
    filters: |
      py_scripts_filter:
        - added|modified: '**/*.py'
```
