### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by iamtodor** [dorny/paths-filter#175]
This is the warning I see every time I my workflow:

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by dorny** [comment]
@iamtodor It's the same as the other issue you have created. You are probably using an old version of this action. This issue was already addressed in the last two releases. Please verify if you are using either `v2.11.1` or `v2` version tags.

**Comment by iamtodor** [comment]
@dorny sorry for the late reply - I just got back from vacation. What is the proper way to verify the version? Here is my configuration:

```yaml
- name: Check for python file changes
  uses: getsentry/paths-filter@v2
  id: filter
  with:
    list-files: 'shell'
    filters: |
      py_scripts_filter:
        - added|modified: '**/*.py'
```
