### ISSUE TITLE
Weird permission issue when tracking changes for new files

### ISSUE THREAD

**Issue by 0xmichalis** [dorny/paths-filter#177]
I have the following workflow in place:
```yml
      - name: Get changed files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: shell
          filters: |
            artifacts:
            - added|modified: 'data/**/*'
      - name: Conditional
        if: steps.changes.outputs.artifacts == 'true'
        run: |
          echo "Tracked artifacts file have changed"
          artifact=${{ steps.changes.outputs.artifacts_files }}
```
It seems that the `added` keyword that helps keep track of new files is causing a permission issue when I am trying to access `steps.changes.outputs.artifacts_files` in the `Conditional` stage.

I have created a repo to reproduce this issue at https://github.com/0xmichalis/testdir - you can check the failure in https://github.com/0xmichalis/testdir/pull/1
