### ISSUE TITLE
Use filter header and name for matrix

### ISSUE THREAD

**Issue by shachar-charno** [dorny/paths-filter#180]
Hi , 

I have a use case where i would need to identify if a group of paths were changed and if so then run matrix job on the relevant path.

for example `filters.yaml` 
```
services:
  - service-a: 'services/a/**'
  - service-b: 'services/b/**'
  - service-c: 'services/c/**'
  - service-d: 'services/d/**'
```

so what i would like to achieve is - if a path under `services` has changed then matrix on service a,b,c,d ( for name extraction )
or on the other hand is there somehow a way to properly extract service/`<NAME>` from the outputs JSON?
