### ISSUE TITLE
Output of job with paths-filter not being passed to dependent job

### ISSUE THREAD

**Issue by jbstewart** [dorny/paths-filter#181]
Hi. Thanks for all your work on this action! I'm using `paths-filter` to selectively deploy components in a monorepo and the outputs of my job that uses `paths-filter` do not make it into a dependent job that references the `paths-filter` job via the needs context. And I have read through pretty much all your issues, and I can't find anything exactly matching this - but apologies if I missed something...

Anyway, here is the job with `paths-filter`:
```
 version-changed:
    name: 🔺 Check for build number changes in Android apps
    runs-on: ubuntu-latest
    if: ${{ ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev') && github.event_name == 'push' }}

    outputs:
      version: ${{ steps.changes.outputs.version }}
      truck_sprayer: ${{ steps.changes.outputs.version || steps.changes.outputs.truck_sprayer }}
      truck_sim: ${{ steps.changes.outputs.version || steps.changes.outputs.truck_sim }}
      spray_trax: ${{ steps.changes.outputs.version || steps.changes.outputs.spray_trax }}
      spray_trax_mini: ${{ steps.changes.outputs.version || steps.changes.outputs.spray_trax_mini }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check for modified build numbers
        uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ github.ref }}
          filters: | 
            version: 
              - modified: version.txt
            truck_sprayer:
              - modified: Apps/Android/PMG/truck-sprayer/buildNumber.txt
            truck_sim:
              - modified: Apps/Android/PMG/truck-sim/buildNumber.txt
            spray_trax:
              - modified: Apps/Android/PMG/spray-trax/buildNumber.txt
            spray_trax_mini:
              - modified: Apps/Android/PMG/spray-trax-mini/buildNumber.txt

      - name: Debug print change filter results
        run: |
          echo "steps.changes.outputs.version: ${{ steps.changes.outputs.version }}"
          echo "steps.changes.outputs.truck_sprayer: ${{ steps.changes.outputs.truck_sprayer }}"
          echo "steps.changes.outputs.truck_sim: ${{ steps.changes.outputs.truck_sim }}"
          echo "steps.changes.outputs.spray_trax: ${{ steps.changes.outputs.spray_trax }}"
          echo "steps.changes.outputs.spray_trax_mini: ${{ steps.changes.outputs.spray_trax_mini }}"

```

And here is the dependent job:
```
  debug-version-changed-trucksprayer:
    if: ${{ ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev') && github.event_name == 'push' }}
    name: 🕷 DEBUG version-changed Truck Sprayer job
    needs: version-changed
    runs-on: ubuntu-latest
    steps:
      - name: Debug version-changed
        run: echo "${{ needs.version-changed.outputs.truck_sprayer }}"
```

When I change the `Apps/Android/PMG/truck-sprayer/buildNumber.txt` file and push, it runs the workflow, and the results of the `version-changed` job are:

```
*Check for modified build numbers* output:
Run dorny/paths-filter@v2
Get current git ref
Changes will be detected between 3508e30cd2630e6b2ad41738b0b436c2ae7efde3 and master
Ensuring 3508e30cd2630e6b2ad41738b0b436c2ae7efde3 is fetched from origin
Ensuring master is fetched from origin
Change detection 3508e30cd2630e6b2ad41738b0b436c2ae7efde3..master
Detected 2 changed files
Results:
Filter version = false
Filter truck_sprayer = true
  Matching files:
  Apps/Android/PMG/truck-sprayer/buildNumber.txt [modified]
Filter truck_sim = false
Filter spray_trax = false
Filter spray_trax_mini = false
Changes output set to ["truck_sprayer"]
```
Debug print change filter results output:
```
Run echo "steps.changes.outputs.version: false"
steps.changes.outputs.version: false
steps.changes.outputs.truck_sprayer: true
steps.changes.outputs.truck_sim: false
steps.changes.outputs.spray_trax: false
steps.changes.outputs.spray_trax_mini: false
```

And the output of the `debug-version-changed-trucksprayer` job is:
```
Run echo "false"
false
```

I've been beating my head against this problem all afternoon - so I would greatly appreciate any debugging hints or ideas you might have.

**Comment by jbstewart** [comment]
It turns out I had some mistakes in my `version-changed` job, as well as the dependent jobs. When data goes through outputs between *either* GitHub jobs or steps,  it gets converted to strings. So in the output section above, I needed to convert it to :
```
    outputs:
      version: ${{ steps.changes.outputs.version == 'true' }}
      truck_sprayer: ${{ steps.changes.outputs.version == 'true' || steps.changes.outputs.truck_sprayer == 'true' }}
      truck_sim: ${{ steps.changes.outputs.version == 'true' || steps.changes.outputs.truck_sim == 'true' }}
      spray_trax: ${{ steps.changes.outputs.version == 'true' || steps.changes.outputs.spray_trax == 'true' }}
      spray_trax_mini: ${{ steps.changes.outputs.version == 'true' || steps.changes.outputs.spray_trax_mini == 'true' }}
```

And in the dependent jobs be sure to use:
```
needs.version-changed.outputs.truck_sprayer == 'true'
```
instead of:
```
needs.version-changed.outputs.truck_sprayer
```

This has evidently tripped up a lot of other people:
https://github.com/actions/runner/issues/1483
