### ISSUE TITLE
Document usage in a merge queue

### ISSUE THREAD

**Issue by AntonNiklasson** [dorny/paths-filter#183]
I'm using this action in a merge queue. I'm not sure I've gotten all the details right just yet, but I think it works.

Merge queues are still in beta: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

The main issue I ran into was that there was no git repository available by default, like you get on the `pull_request` event. I'm currently doing this:

```
  files-changed:
    runs-on: [ self-hosted ]
    outputs:
      any: ${{ steps.changes.outputs.any }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ github.event.merge_group.base_ref}}
          ref: ${{ github.event.merge_group.head_ref }}
          filters: |
            ui:
              - 'ui/**'
```
