### ISSUE TITLE
How to get intuitive usage when mixing file paths and ignore paths?

### ISSUE THREAD

**Issue by ross-nordstrom** [dorny/paths-filter#184]
I found when I use **"exclude paths"**, then my filter always produces a **false positive** causing my workflow to do the wrong thing.

Example:
```yaml
      - uses: dorny/paths-filter@v2
        id: services
        with:
          filters: |
            ui:
              - 'ui/**'
              - '!ui/README.md'
              - '!ui/cypress/**'
```

## Use Case
I'm using this to drive a build matrix on only my changed services, so I'm making use of the slick `.changes` property you produce

```yaml
      services: ${{ steps.services.outputs.changes }}
```

## Workaround
To make this work, I've switched my filters to ONLY use "include paths." 

```yaml
          filters: |
            ui:
              - 'ui/package*.json'
              - 'ui/angular.json'
              - 'ui/Dockerfile'
              - 'ui/Dockerfile'
              - 'ui/nginx.conf'
              - 'ui/src/**'
              - 'ui/ui/**/*.{yml,yaml}'
```

# Expectation
When `!` paths (exclude paths) are in the filter, the filter should be true iff `any(include_paths) && all(exclude_paths)`.

Maybe my expectation is actually possible, and I'm just missing an option somewhere??

**Comment by makenosound** [comment]
I have exactly the same use-case described here, and would love to see it as a native option in the action.

**Comment by ja-leo** [comment]
same here, it would be great to see this working with the excludes flag

**Comment by francisInfact** [comment]
Also have the same issue - expectation would be that the filter would be true if **all** rules match.

**Comment by DavidVaness** [comment]
I ran into this today, really cumbersome for us because I have 2 files per app per filter I need to ignore (package.json & CHANGELOG.md) in our monorepository. The consequence of targeting all subdirectories and files to ignore these is a bit problematic because it if a dev adds a new file / directory it will be ignored then, very brittle.

**Comment by hintron** [comment]
I think can be solved by changing the predicate-quantifier to 'every' (added in #224). The only problem is that it seems to be in a broken state, and the maintainer has not yet merged in the fix in #225.

**Comment by gylove1994** [comment]
I fork it and added an 'ignore' option [here](https://github.com/gylove1994/paths-filter).

**Comment by ncelisabet** [comment]
I had a simpler use case and was able to get a workaround working. I wanted a filter that returned true if any file was changed in a folder, except for one of its subfolders. I did expect the filter to be true if _all_ filters matched, but unfortunately that is not the case. I compared the numbers of matching files instead, it looks like this:

        paths-filter:
          runs-on: ubuntu-latest
          outputs:
            mainfolder: ${{ steps.filter.outputs.mainfolder == 'true' && steps.filter.outputs.mainfolder_count != steps.filter.outputs.subfolder_count }}
            subfolder: ${{ steps.filter.outputs.subfolder }}
          steps:
            - uses: actions/checkout@v4
            - uses: dorny/paths-filter@v3
              id: filter
              with:
                filters: |
                  mainfolder:
                    - 'mainfolder/**'
                  subfolder:
                    - 'mainfolder/subfolder/**'

**Comment by gylove1994** [comment]
> I had a simpler use case and was able to get a workaround working. I wanted a filter that returned true if any file was changed in a folder, except for one of its subfolders. I did expect the filter to be true if _all_ filters matched, but unfortunately that is not the case. I compared the numbers of matching files instead, it looks like this:
> 
> ```
>     paths-filter:
>       runs-on: ubuntu-latest
>       outputs:
>         mainfolder: ${{ steps.filter.outputs.mainfolder == 'true' && steps.filter.outputs.mainfolder_count != steps.filter.outputs.subfolder_count }}
>         subfolder: ${{ steps.filter.outputs.subfolder }}
>       steps:
>         - uses: actions/checkout@v4
>         - uses: dorny/paths-filter@v3
>           id: filter
>           with:
>             filters: |
>               mainfolder:
>                 - 'mainfolder/**'
>               subfolder:
>                 - 'mainfolder/subfolder/**'
> ```

Seem the [fork one](https://github.com/gylove1994/paths-filter) could ment your need :

```
        with:
          filters: |
            mainfolder:
              pattern:
                 - 'mainfolder/**'
              ignore:
                 - 'mainfolder/subfolder/**'
             subfolder:
              pattern:
                 - 'mainfolder/subfolder/**'
  ```

**Comment by vleague2** [comment]
I had a similar use case and found a solution based on the underlying [picomatch library docs](https://github.com/micromatch/picomatch?tab=readme-ov-file#globbing-features) (you can also test with this [picomatch playground](https://picomatch-playground-ebjlxm.csb.app/)):
```
with:
  filters: |
    files:
      - "mainfolder/!(subfolder)/**"
```
This will match `mainfolder/something/file.ts` and `mainfolder/file.ts` but not `mainfolder/subfolder/file.ts`. You can also do `mainfolder/!(subfolder|anotherSubfolder)/**` for multiple exclusions.
