### ISSUE TITLE
How to use paths-filter in reusable github action workflows

### ISSUE THREAD

**Issue by hex0cter** [dorny/paths-filter#192]
When using this action as a step in a reusable github action workflow, the git ref is the branch name of the calling repository instead of the called repository.

For example, in repo B, there is a reusable workflow b.yaml, which uses below as a step:

```yaml
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref_name }}
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
``` 

In repo A there is another workflow a.yaml that calls B/b.yaml. Now if someone pushes a commit which triggers a.yaml, which then triggers b.yaml, `dorny/paths-filter` will fail because the `github` context comes from repository A instead repository B, because the branch name from repo A doesn't exist in repo B.

Is there any solution for this?

Reference: https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow
> When a reusable workflow is triggered by a caller workflow, the github context is always associated with the caller workflow. The called workflow is automatically granted access to github.token and secrets.GITHUB_TOKEN. For more information about the github context, see "[Contexts](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context)."
