### ISSUE TITLE
Exclude few folders in one filter

### ISSUE THREAD

**Issue by oleksandr-kinship** [dorny/paths-filter#200]
Hey, have repo that include two folders, for which I don't want to run some steps, tried following:
```
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            ga:
              - '!.github/**'
            infra:
              - '!infrastructure/**'
            ga-infra:
              - '!.github/**'
              - '!infrastructure/**'  
     ```
     Got this results:
     
     ```
     Results:
Filter ga = true
  Matching files:
  infrastructure/src/resources/liquibase.ts [modified]
  src/main/java/com/.../file.java [modified]
Filter infra = true
  Matching files:
  .github/workflows/document_tests.yml [modified]
  src/main/java/com/.../file.java [modified] [modified]
Filter ga-infra = true
  Matching files:
  .github/workflows/document_tests.yml [modified]
  infrastructure/src/resources/liquibase.ts [modified]
  src/main/java/com/.../file.java [modified] [modified]
  ```
  
  `ga` and `infra` looks good, expected that some folders not match, but in `ga-infra` I expected to see only `src/main/java/com/.../file.java` because other excluded
  Can you point me what I did wrong or this not possible to implement, tried to read `picomatch` not get answers ..

**Comment by y-takebe** [comment]
@oleksandr-kinship 

I had the same problem recently, but it seems that the negation operator is not supported.
Please also check the following related issue

- https://github.com/dorny/paths-filter/issues/106
- https://github.com/dorny/paths-filter/pull/151

I'd be happy if it's the same as GitHub's paths.

**Comment by oleksandr-kinship** [comment]
> @oleksandr-kinship
> 
> I had the same problem recently, but it seems that the negation operator is not supported. Please also check the following related issue
> 
> * [exclude files or dir #106](https://github.com/dorny/paths-filter/issues/106)
> * [Proposing v3.0.0 with updates and new features #151](https://github.com/dorny/paths-filter/pull/151)
> 
> I'd be happy if it's the same as GitHub's paths.

Thanks, it works for single rule but not in combination..
so I was tried another action, for me in general it's less comfortable, but at least it works fine so far,
here is example
```
      - name: Get changes
        uses: tj-actions/changed-files@v38
        id: changes
        with:
          files_yaml: |
            non-infra:
              - '!.github/**'
              - '!infrastructure/**'
              
      - name: Log non-infra changes
        shell: bash
        run: |
          echo "Is there changes for non-infra: ${{ steps.changes.outputs.non-infra_any_changed}}"
          echo "List of all non-infra changed files: ${{ steps.changes.outputs.non-infra_all_changed_files }}"

```

**Comment by Qix-** [comment]
It appears that `!foo` is returning a list of files from the _entire_ folder that do not match `foo`, instead of culling the existing filepaths from other lines. The underlying `minimatch`/`picomatch` libs are working as expected.

In our case, our filter was previously

```yaml
- app-*/**
- !app-ui/**
```

but I'm pretty sure that resulted in a union of:

- everything in `app-*/**` (including `app-ui`)
- **plus** everything that didn't match `app-ui/**

resulting in a file list that includes *everything in the folder* as triggering a rebuild.

Instead, we changed to

```yaml
- app-!(ui)/**
```

which is what we wanted. That syntax is described on [`picomatch`'s docs](https://github.com/micromatch/picomatch), which is what this action uses.

**Comment by saschabratton** [comment]
Good news, this is doable now 👍🏻 the piece that was missing when you filed this is the `predicate-quantifier` option (landed in v3.0.2). By default a file matches a filter if it matches _any_ of the patterns (`some`), which is why your `ga-infra` filter was matching files in either dir. If you flip it to `every`, a file only counts when it matches _all_ the patterns, so the negations actually stack:

```yaml
- uses: dorny/paths-filter@v3
  with:
    predicate-quantifier: every
    filters: |
      ga-infra:
        - '!.github/**'
        - '!infrastructure/**'
```

Now `ga-infra` is only `true` for changes outside both `.github` and `infrastructure`. There's an example of this in the predicate-quantifier section of the README too. (Heads-up that it's a step-level setting, so it applies to all filters in that step... which is fine here since your single-pattern filters behave the same either way.)

Going to close this out since it's supported now, but lmk if it doesn't behave 🙏🏻
