### ISSUE TITLE
Changed files with git commands detects too many files

### ISSUE THREAD

**Issue by mirpedrol** [dorny/paths-filter#205]
Hello!

We are using this GitHub Action with the modification in https://github.com/dorny/paths-filter/pull/133 to avoid reaching the API Rate limit. 
Using git commands, the action paths filter uses the command `git rev-parse HEAD` to obtain the last commit. In PR events, this is the pre merge commit id. Because of that, we see too many files changed, not only the ones in the current PR.

One solution is to use `git rev-parse HEAD^2` instead, in order to obtain the real last commit from the PR branch.
In the GitHub workflow yaml file, the following must also be added:
```
- uses: actions/checkout@v4
        with:
          fetch-depth: 2 # To retrieve the preceding commit.
```
 
I'm happy to open a PR to address this if you think it's the right way to go :)

**Comment by saschabratton** [comment]
@mirpedrol Would something like this work for your use case?

```yaml
  - uses: actions/checkout@v6
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      fetch-depth: 0
```
