### ISSUE TITLE
Is it possible to check if a single folder has changed?

### ISSUE THREAD

**Issue by guy-frontegg** [dorny/paths-filter#207]
Hey,

Thank you very much for this action, it is great.

I have a question I could not find an answer to, is it possible to check if a file has change in a specific folder and nothing else in the repository?

for example:
folder_A
   x.txt
folder_B
folder_C
file.1
file.2

How to know if file X.txt is the only thing that changes in this commit and nothing else?

BTW the structure is not constant only the name of the folder itself

**Comment by SethFalco** [comment]
Your question is very unclear. It sounds like you want one of the following configurations, though.

This would match if only the contents of the directory or subdirectory named `folder_A` has changed.

```yml
- uses: dorny/paths-filter@v2
  with:
    filters: |
      src:
        - '**/folder_A/**'
```

This would match if the file `x.txt` changed, regardless of which directory it's found in.

```yml
- uses: dorny/paths-filter@v2
  with:
    filters: |
      src:
        - '**/x.txt'
```

**Comment by guy-frontegg** [comment]
Thank you for your answer, :)
My question was let's say that I want to know if 
````yaml
- uses: dorny/paths-filter@v2
  with:
    filters: |
      src:
        - '**/x.txt'
 ````
 and only this file and nothing else. But I found the answer so we can close this issue.
 Thank you

**Comment by jgehrcke** [comment]
> But I found the answer

What was the answer?

**Comment by jgehrcke** [comment]
> This would match if only the contents of the directory or subdirectory named folder_A has changed:
```
- uses: dorny/paths-filter@v2
  with:
    filters: |
      src:
        - '**/folder_A/**'
```
I haven't tested this, but it appears to me that this does not automatically switch to `false` when say, both of these paths have been changed:
- `/folder_A/file`
- `/foo`

It appears to me that the above's rule would be unimpressed by the change to `/foo` and just output that "yes, something changed matching the pattern `**/folder_A/**`.

**Comment by jgehrcke** [comment]
I used https://github.com/tj-actions/changed-files which delivers this with its `only_changed` output parameter.

Example:
```yaml
    - name: changed-files-for-skip
      id: changed-files-for-skip
      uses: tj-actions/changed-files@v45
      with:
        files: |
          docs/**

...

    - name: Skip next?
      shell: bash
      run: |
        echo "Skip the next step if only_changed is true"
        echo "steps.changed-files-for-skip.outputs.only_changed:"
        echo "${{ steps.changed-files-for-skip.outputs.only_changed }}"

...

    - name: some costly stuff
      # only skip if changes are limited to patterns above.
      if: steps.changed-files-for-skip.outputs.only_changed != 'true'
      shell: bash
      run: echo "foo"
      
```
