### ISSUE TITLE
filter in folder changes does not seem to work

### ISSUE THREAD

**Issue by LayMui** [dorny/paths-filter#208]
- uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          coffee-club: |
            packages/coffee-club/**
            envs/coffee-club-.*

I made changes to the files at packages/coffee-club/package.json

but the ci shows 

Detected 14 changed files
Results:
Filter coffee-club = false
  Matching files: none
Changes output set to []

**Comment by SethFalco** [comment]
It's difficult to tell because the formatting it messed up, but I'm guessing you made a mistake in your configuration. Can you fix the formatting of your config in the issue? It looks like you defined your `filters` wrong currently.

It should be more like this, namely that you haven't indented your config correctly and are missing the YAML array syntax.

```yml
uses: dorny/paths-filter@v2
with:
  filters: |
    coffee-club:
      - 'packages/coffee-club/**'
      - 'envs/coffee-club-.*'
```
