### ISSUE TITLE
Error: Unable to locate executable file: git

### ISSUE THREAD

**Issue by phavekes** [dorny/paths-filter#212]
I use this in my github action:
```
      # Check for changes in the server component of the Archimate model
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            archi:
              - 'docs/invite.archimate'
            server:
              - 'server/src/**'
```
This was working fine previously, but now the github action complains about missing the git executable:
```
Run dorny/paths-filter@v2
Get current git ref
Error: Unable to locate executable file: git. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

**Comment by dorny** [comment]
@phavekes This action expects the git executable to be available in the PATH. Which runner do you use? Can you write here value of [runs-on](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on) field of your job?

**Comment by wweaver** [comment]
I'm using v3 and getting this error as well.

```
Get current git ref
  /usr/bin/git branch --show-current
  fatal: not a git repository (or any of the parent directories): .git
Error: The process '/usr/bin/git' failed with exit code 128
```
<img width="569" alt="image" src="https://github.com/dorny/paths-filter/assets/1482976/0993db64-f802-4e90-9dc3-ca9b786ce44a">


```yaml
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      ...
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ...
```

What's weird is this is working for me on a `pull_request` trigger, but it's not working on a `push` trigger. Could this be github not providing git in the path for `push` triggers?
