### ISSUE TITLE
VSCode "Context Access might be invalid" warning

### ISSUE THREAD

**Issue by thoughtfuldata** [dorny/paths-filter#223]
im getting this warning when using 

```
- uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          made-up-name:
            - 'made-up-name/**'
```

with 
```
- name: Build image and push to Docker Hub
      uses: docker/build-push-action@v5
      if: steps.changes.outputs.book-made-up-name == 'true'
      with:
          context: REMOVED
          tags: REMOVED
          push: true
```
        
` if: steps.changes.outputs.book-made-up-name == 'true' `      This is where the error appears. I only get this error with this github action
