### ISSUE TITLE
[Help Wanted] Multiple negations in a file path of filters is not working as expected

### ISSUE THREAD

**Issue by prathamVaidya** [dorny/paths-filter#228]
## Issue

Adding Multiple negations of the file path gives `true` value when it should be `false`.

## Code

This is my workflow file:

```
name: main-ci
on: ['push', 'pull_request']
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2

        - uses: dorny/paths-filter@v3
          id: filter
          with:
            filters: |
                backend:
                    - '!docs/**'
                    - '!frontend/**'

        - name: Lint Backend
          if: ${{ steps.filter.outputs.backend == 'true' }}
          run: echo "Doing Backend";  pwd
```

In the filters backend this `!frontend/**`  file path is working but if I add two negations in the file path then it's not working. 
Even this file path is working ` - '!(docs|frontend)/**'`
My expected behaviour is that backend should be any file & folder that is not docs and frontend. When I push any file in `docs` or `frontend` folder then backend filter should be `false` but it is `true`.

I think I am missing something very obvious but can't figure out even after hours of debugging and trying different ways of file paths. Any help is appreciated.
