### ISSUE TITLE
Force Push Unexpected Behavior

### ISSUE THREAD

**Issue by 4r7if3x** [dorny/paths-filter#240]
I noticed the test would not work as expected when a force push happens, since the pushed commit is checked against itself, hence only the changes in comparison with the previous version of the commit are put into consideration. Although this looks to be the correct behavior, it can cause issues in some scenarios as I expected to detect the existence of the filter in the pushed commit.

Since I believe both behaviors can be beneficial to certain needs, can we have an additional option for this action to let us choose between the two? Or is it currently hackable through the current options?

**Comment by ajgon** [comment]
For everyone stumbling upon this problem (as I did), here is a workaround:

```yaml
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # important, to fetch previous commit

      # workaround for https://github.com/dorny/paths-filter/issues/240
      - id: previous-sha
        run: 'echo "sha=$(git rev-list -n 1 ${{ github.ref }}^)" >> $GITHUB_OUTPUT'

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: "${{ steps.previous-sha.outputs.sha }}"
          filters: |
            myfilters: ./**/*

**Comment by Time0o** [comment]
> For everyone stumbling upon this problem (as I did), here is a workaround:
> 
>       - uses: actions/checkout@v4
>         with:
>           fetch-depth: 2  # important, to fetch previous commit
> 
>       # workaround for https://github.com/dorny/paths-filter/issues/240
>       - id: previous-sha
>         run: 'echo "sha=$(git rev-list -n 1 ${{ github.ref }}^)" >> $GITHUB_OUTPUT'
> 
>       - uses: dorny/paths-filter@v3
>         id: filter
>         with:
>           base: "${{ steps.previous-sha.outputs.sha }}"
>           filters: |
>             myfilters: ./**/*

I just had the same issue and this looks reasonable but wouldn't you want to use `git fetch origin/main && git rev-parse origin/main` instead of `${{ github.ref }}` to diff against?

**Comment by streambinder** [comment]
Simplified variant of the workaround above — `git rev-parse HEAD~1` avoids injecting `${{ github.ref }}` into the shell and is equivalent since the checkout already points HEAD at the pushed commit:

```yaml
- uses: actions/checkout@v4
  with:
    fetch-depth: 2
    persist-credentials: false
- id: parent
  run: echo "sha=$(git rev-parse HEAD~1)" >> "$GITHUB_OUTPUT"
- uses: dorny/paths-filter@v3
  id: filter
  with:
    base: ${{ steps.parent.outputs.sha }}
    filters: |
      src:
        - 'src/**'
```

`fetch-depth: 2` is sufficient — only the parent commit is needed for the diff. No need for full history.

Regarding `origin/main` (from the comment above): that would diff against the tip of the default branch, not the previous commit on the same branch. For push-to-master workflows where you want "what changed in this push", `HEAD~1` is the correct base.
