### ISSUE TITLE
remote: Repository not found

### ISSUE THREAD

**Issue by razb-viola** [dorny/paths-filter#243]
I get this error:

```
remote: Repository not found.
  Error: fatal: repository 'https://github.com/REPO/' not found
  The process '/usr/bin/git' failed with exit code 128
  Waiting 14 seconds before trying again
```

And this is the workflow yaml:

```
- uses: actions/checkout@v4
- uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            auth:
              - 'backend/auth/src/**'
```

and the step of dorny gets the error mentioned above - without reaching to the step of running the service later in the yaml, that's why I didn't provide it here.

I tried both checkout@v4 and v3.
I gave permissions of pull request read, as follow:

```
permissions:
      pull-requests: read
```
