### ISSUE TITLE
Detect changes against most recent commit in PR instead of just on push 

### ISSUE THREAD

**Issue by weiligao** [dorny/paths-filter#249]
Currently it's only possible to detect changes against most recent commit if triggered by `push` using `base: ${{ github.ref }}`, it would be nice if it would also be supported for trigger `pull_request`.

**Comment by flucrezia** [comment]
I think I'm running into this issue but I am not sure.

I have the following:
```
on: 
  pull_request:
    branches:
      - master
      - release/*
...
jobs:
  update-dockers:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
...
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Filter Dockerfile changes
        uses: $dorny/paths-filter@v3
        id: filter
        with:
          list-files: shell
          filters: |
            dockerfile:
              - added|modified: 'Dockerfile.*'
```
Then I push on a PR branch a change that affects a file detected by the filter (at lease on push events):

```
::group::Fetching list of changed files for PR#492 from Github API
Invoking listFiles(pull_number: 492, per_page: 100)
Received 2 items
[changed] .gitea/workflows/main.yml
[changed] Dockerfile.deb11.6
::endgroup::
Detected 2 changed files
Results:
::group::Filter dockerfile = false
Matching files: none
::endgroup::
Changes output set to []
```

There is any matching, but 'Dockerfile.deb11.6' should have matched! 
Am I missing something ?
Many thanks,
Francesco
