### ISSUE TITLE
GitHub Actions VSCode plugin warns context access is invalid with output example given in README.md

### ISSUE THREAD

**Issue by johnseth97** [dorny/paths-filter#251]
The following code produces the above warning on lines 9 && 10

```
jobs:
    determine-changes:
        name: Determine Changes
        runs-on: ubuntu-latest
        permissions:
            pull-requests: read
            contents: read
        outputs:
            frontend: ${{ steps.changes.outputs.frontend }}
            backend: ${{ steps.changes.outputs.backend }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Filter changed files
              id: changes
              uses: dorny/paths-filter@v3
              with:
                  filters: |
                      frontend:
                        - 'frontend/**'
                      backend:
                        - 'backend/**'
```

The following code, setting a default value, seems to fix it for me: 

```
jobs:
    determine-changes:
        name: Determine Changes
        runs-on: ubuntu-latest
        permissions:
            pull-requests: read
            contents: read
        outputs:
            frontend: ${{ steps.changes.outputs.frontend || false }}
            backend: ${{ steps.changes.outputs.backend || false }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Filter changed files
              id: changes
              uses: dorny/paths-filter@v3
              with:
                  filters: |
                      frontend:
                        - 'frontend/**'
                      backend:
                        - 'backend/**'
```
