### ISSUE TITLE
Filtering just first-leve files (excluding subfolders) doesn't work

### ISSUE THREAD

**Issue by cusma** [dorny/paths-filter#257]
Filtering changes on just first-level files in a folder (ignoring subfolders) doesn't work.

An example of what I'm trying to do:

```yaml
- name: Detect changes
  uses: dorny/paths-filter@v3
  id: filter
  with:
    filters: |
      test-config:
        - 'tests/*(.).py'
```
