### ISSUE TITLE
Filtering out markdown files when there are multiple possible positive matches?

### ISSUE THREAD

**Issue by Time0o** [dorny/paths-filter#260]
I have not been able to get this to work and it seems like a common use case: I want to match a filter if either rule A or rule B matches but ignore any changes to e.g. `*.md` files. This does not work:

```
with:
  filters: |
    foo:
      - foo/a/**
      - foo/b/**
      - !**/*.md
  predicate-quantifier: 'every'
```

Because now `foo` will only match if files in `a` AND `b` have changed. What can I do here or is this simply not implemented?
