### ISSUE TITLE
Bug: `'before' field is missing` when it should not even be used

### ISSUE THREAD

**Issue by rschristian** [dorny/paths-filter#261]
We're using this action in a workflow triggered via `workflow_run`, using it to report on another action that takes place in our repository. To ensure the correct context, use set both `base` & `ref` to ensure the head of a PR is compared against the head of the base branch.

From PRs, however, this action is throwing the following warning:

```
Warning: 'before' field is missing in event payload - changes will be detected from last commit
```

It then proceeds to mark every single file in the repo as "changed", breaking any attempt at filtering.

I don't see why it'd matter that a `'before' field is missing`, we have the commit SHAs this action needs to compare.

**Comment by Neogentai** [comment]
Hitting this on `v3` with a `workflow_run` trigger (no fork involvement — same-repo). Sharing a focused repro and root-cause walk-through in case it helps prioritize a fix.

## Repro shape

```yaml
on:
  workflow_run:
    workflows: ["Some Other Workflow"]
    types: [completed]
    branches: [main]

jobs:
  publish:
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: 'main'
          # ref intentionally omitted — relying on default
          filters: |
            wolfi:
              - 'some/path/**'
```

Every run on `main` (post version-bump) emits `Warning: 'before' field is missing in event payload - changes will be detected from last commit` and the filter returns the wrong answer.

## Root cause walk-through

In `getChangedFilesFromGit` (current `v3`):

```ts
head = git.getShortName(head || github.context.ref || currentRef)
//                              └────────┬───────┘
//        on workflow_run, context.ref = "refs/heads/main" → getShortName → "main"

base = git.getShortName(base || defaultBranch)   // "main" → "main"

const isBaseSha       = git.isGitSha(base)       // false
const isBaseSameAsHead = base === head           // TRUE — both "main"

if (isBaseSha || isBaseSameAsHead) {             // ← entered via the second condition
  const baseSha = isBaseSha ? base : beforeSha   // beforeSha is null on workflow_run
  if (!baseSha) {
    core.warning(`'before' field is missing in event payload …`)
    return await git.getChangesInLastCommit()    // ← wrong answer
  }
}
```

So the warning isn't actually about a missing `before` field per se — it's about the action *needing* `before` because it routed itself into the `isBaseSameAsHead` branch when `base` and `head` happen to normalize to the same string. The user's `base` was perfectly valid; the action just refuses to use it for a merge-base diff once `isBaseSameAsHead === true`.

## Workaround (works for our shape)

Pass `ref` explicitly as a SHA so `head !== base` after `getShortName`:

```yaml
with:
  base: 'main'
  ref: ${{ env.RESOLVED_SHA }}      # github.event.workflow_run.head_sha for this trigger
```

Plus `fetch-depth: 0` on the prior checkout so `getChangesSinceMergeBase` has both refs locally.

This routes execution to the correct path:

```ts
core.info(`Changes will be detected between ${base} and ${head}`)
return await git.getChangesSinceMergeBase(base, head, initialFetchDepth)
```

## Suggested fix

The `isBaseSameAsHead` short-circuit assumes that when `base === head` the user must want a "what changed in the last commit on this ref" answer. That's only valid when `head` is *implicit*. When the user explicitly passed `base` AND `ref` (as our case and the OP's case do), the safer assumption is "do a merge-base diff between these two refs, even if they happen to be string-equal." Concretely: gate `isBaseSameAsHead` on `head` having been left as default (i.e. `inputs.ref` was not provided) instead of on the post-normalization string comparison.

Happy to send a PR if you'd take it.
