### ISSUE TITLE
Use strategy matrix to check if paths was changed

### ISSUE THREAD

**Issue by Shatur95** [dorny/paths-filter#27]
For example, I have `targets` array in my matrix. Then I use this action to detect changed changed with filters named exactly the same as `targets`:

```yml
jobs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        target: [first, second]
    steps:
    - name: Detect changes
      uses: dorny/paths-filter@v2.2.0
      id: changes
      with:
        filters: |
          first:
            - /some/path/**
          second:
            - some/another/path/**
```

Is there a way to check if matrix `target` was filtered? Something like the following:

```yml
    - name: My Action
      if: contains(steps.changes.outputs, matrix.target)
      run: echo "test"
```

**Comment by Shatur95** [comment]
I found a way!
`contains(toJson(steps.changes.outputs), matrix.target)`

**Comment by MartinNowak** [comment]
Doesn't this run your detect changes for each matrix entry? If that's intended, you could just make the matching path a parameter of the matrix. Sth. like this (untested):
```yaml
jobs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        target:
          - name: first
            paths: /some/path/**
          - name: second
            paths: some/another/path/**
    steps:
    - name: Detect changes
      uses: dorny/paths-filter@v2.2.0
      id: changes
      with:
        filters: |
          matched:
            - ${matrix.target.paths}
```

**Comment by Shatur95** [comment]
Yes, this is a good idea too! But this will not possible for multiply paths:

```yml
    - name: Detect changes
      uses: dorny/paths-filter@v2.2.0
      id: changes
      with:
        filters: |
          first:
            - some/path/**
            - some/another/path/**
```
