### ISSUE TITLE
Add paths-ignore

### ISSUE THREAD

**Issue by InsonusK** [dorny/paths-filter#28]
I offer to make two changes:
1) rename input parameter filters to paths, so it looks like [workflow event](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths)
2) add paths-ignore: set true if at least one file doesn't match any path in filter group

**Comment by dorny** [comment]
Thanks for the offer :)

Regarding 1)
In the beginning of the project I actually decided to not try it to look like the workflow event `paths` option.
The reason was that workflow `paths` option is directly list of paths while this action accepts several lists, each given a name.
Also here we use [minimatch](https://github.com/isaacs/minimatch), while workflow uses some custom syntax.
This differences could be confusing for the user. Well, I'm really not sure if it was a good decision, but it's already there.
If we should change it, then I would do it on the `develop` branch together with other changes and release them together.
I will think about it.

Regarding 2)
Could you please add some example use case? I'm not sure if I get correctly how it should work.

**Comment by InsonusK** [comment]
Regarding 2)
for example I have such repo
- src
- .gitignore
- .github
- README.md

In workflow I want to check if pull request change only files in src folder or other files. So I need check in workflow
```
- uses: dorny/paths-filter@v2.2.1
  name: "src files changes
  id: filter
  with:
    paths: |
      src_changed:
        - 'src/**'
    paths-ignore: |
      other_changed:
        - 'src/**'
```

Cases:
1) **changed:** 
- src/index.js
**result:**
- src_changed: true
- other_changed: false

2) **changed:**
- src/index.js
- .gitignore
**result:**
- src_changed: true
- other_changed: true

3) **changed:**
- .gitignore
**result:**
- src_changed: false
- other_changed: true

4) **changed:**
[]
**result:**
- src_changed: false
- other_changed: false

**Comment by InsonusK** [comment]
But while I try to realize it, I understand that it would some troubles with output values. And it will be much easier to add one more parameter: NOT (I am not sure how to call it).

Previous example will be changed like that
```
- uses: dorny/paths-filter@v2.2.1
  name: "src files changes
  id: filter
  with:
    not: true
    paths: |
      src_changed:
        - 'src/**'
```

Cases:
1) **changed:** 
- src/index.js
**result:**
- src_changed: false

2) **changed:**
- src/index.js
- .gitignore
**result:**
- src_changed: true

3) **changed:**
- .gitignore
**result:**
- src_changed: true

4) **changed:**
[]
**result:**
- src_changed: false

**Comment by dorny** [comment]
Ah, got it.
This is actually already supported by [minimatch](https://github.com/isaacs/minimatch#comparisons-to-other-fnmatchglob-implementations) - library which is internally used to evaluate the path matches.

You just have to add leading `!` and wrap the whole path with `'` or `"` as leading exclamation mark has some special meaning in YAML.

Given your first example, I think this should work fine:
```yaml
- uses: dorny/paths-filter@v2.2.1
  name: "src files changes
  id: filter
  with:
    paths: |
      src_changed:
        - 'src/**'
      other_changed:
        - '!src/**'
```

Could you please verify if it works for your use-case?
