### ISSUE TITLE
Trigger on `pull_request.labeled`

### ISSUE THREAD

**Issue by bittelc** [dorny/paths-filter#36]
If I have a workflow event with trigger:
```
on:
  pull_request:
    types:
    - labeled
```
and my job looks like:
```
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2.2.1
      id: filter
      with:
        filters: |
          :migrations
            - 'db/**/*'
    - name: deploy
      if: steps.filter.outputs.migrations == 'false'
      run: ...
```

The above `deploy` step will always run, even if there are changes to the `db` directory.

I believe this is because the `pull_request` event that you're using in your GitHub Action doesn't support the `labeled` type.
