### ISSUE TITLE
error::Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by kiptoomm** [dorny/paths-filter#39]
G'day: 

I am testing this action [locally with act](https://github.com/nektos/act) like so:

`act -j deployToFirebase -v`

My stack:
- macOS Catalina
- node v14.3.0
- yarn 1.22.5
- act 0.2.14

I am running into a problem, and here's the partial stack trace:

```
[Build and Deploy to Firebase/deployToFirebase] Exec command '[node /actions/dorny-paths-filter@v2/dist/index.js]'
[Build and Deploy to Firebase/deployToFirebase]   ❗  ::error::Cannot read property 'startsWith' of undefined
[Build and Deploy to Firebase/deployToFirebase]   ❌  Failure - dorny/paths-filter@v2
...
DEBU[0040] exit with `FAILURE`: 1
DEBU[0040] exit with `FAILURE`: 1
DEBU[0040] exit with `FAILURE`: 1
Error: exit with `FAILURE`: 1
```

My workflow file `deployToFirebase.yml` looks like:

```
name: Build and Deploy to Firebase

on:
  push:
    branches: [ develop ]

jobs:
  deployToFirebase:

    runs-on: ubuntu-latest
    env:
      CI: ""

    steps:
    - name: Check out code
      uses: actions/checkout@master
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          frontend:
            - 'src/**'
          backend:
            - 'functions/**'

     # run only if 'frontend' (hosting) files were changed
    - name: frontend steps
      if: steps.filter.outputs.frontend == 'true'
      run: |
        echo "<<<<<<<<<<<<<<<<<<<<<<< frontend changed"
     # run only if 'backend' (functions) files were changed
    - name: functions steps
      if: steps.filter.outputs.backend == 'true'
      run: |
        echo ">>>>>>>>>>>>>>>>>>>>>>> functions changed"
```

**What am I not doing right? Or is there anything special I have to do in order to use this action?**

I am also open to suggestions on how else to test locally to save on the hassle of first sending the code to github and then waiting for the workflow result
