### ISSUE TITLE
allow filtering on all event types

### ISSUE THREAD

**Issue by rexfleischer** [dorny/paths-filter#43]
It would be useful if this could filter based on changes to HEAD. I've ran into patterns where I want to send dispatches to start other workflows for syncing translations or uploading changed assets. But those jobs cannot use this because it gets the error: `This action can be triggered only by pull_request or push event`

Thanks for the work!

**Comment by dorny** [comment]
I'm not exactly sure what do you mean by changes to HEAD.

Anyway I could make it work for any event the same way as it currently works for push events:
- For feature branches changes would be detected against the merge-base with base branch
- For change detection since previous push you could pass the "before" commit SHA using `workflow_dispatch` inputs and use it as a `base` parameter for this action.
- As a fallback if there is no base branch or SHA of previously pushed commit, it would consider only changes in the last commit

Would this work for you?

**Comment by rexfleischer** [comment]
yea. that'd be awesome. and all those sound really useful as well (especially the before commit one).

for more context on what I'm trying to do. I'm starting to split out workflows because the jobs are getting really large. I'm sending a couple repository dispatch events every time a merge happens to master. So, I really just want to check for changes on the last commit on the current branch that is checked out. sorry, it's been a long day so I hope I'm still making sense :)

**Comment by dorny** [comment]
Ok, so the idea is clear now. Implementing the changes should be quite easy. I plan to do it later today.

**Comment by dorny** [comment]
Should work now. I tested it with example bellow.
Please reopen this issue if you will still run into some issues.

> Thanks for the work!

Consider starring the repo :)

## Example:
First workflow which triggers the second one:
```
name: "Dispatch"
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke workflow with inputs
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: PostBuild
        token: ${{ secrets.PERSONAL_TOKEN }}
        inputs: '{ "before": "${{ github.event.before }}" }'
```

Follow up workflow:
```
name: "PostBuild"
on:
  workflow_dispatch:
    inputs:
      before:
        description: 'SHA of last previously pushed commit'
        required: true

jobs:
  post-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.event.inputs.before }}
        filters: ...
```
