### ISSUE TITLE
Getting error "not a git repository (or any of the parent directories)"

### ISSUE THREAD

**Issue by MaicolBen** [dorny/paths-filter#60]
Hey!

<img width="547" alt="Screen Shot 2021-01-05 at 11 04 34" src="https://user-images.githubusercontent.com/3474627/103655300-cddbbd80-4f45-11eb-84a5-016550927ea2.png">

What could be missing? Do I need to give special permissions? Thanks

**Comment by dorny** [comment]
Hey!

As the error message says - current working directory is not part of git repository. This could be caused by:
1. You didn't cloned the repository first
2. You cloned the repository to some subfolder

This action can also work without local clone of repo but it works only for pull requests.
To clone the repository put `- uses: actions/checkout@v2` before this action is executed.
If you cloned repository to different path you have to set correct path with `working-directory` input variable.

**Comment by MaicolBen** [comment]
I didn't know about the `uses: actions/checkout@v2 `, thanks!

**Comment by neilmenon** [comment]
I did not know about checking out either and had a hard time finding this info. Could it be added to the documentation somewhere as a note? I'm relatively new to Github Actions. Thanks for your work!

**Comment by jefffroman** [comment]
Seconded, while it seems obvious that the repo would need to be checked out, the fact that it works for a PR without checkout is a bit of a juke.

**Comment by mvhatch** [comment]
Running into the same issue, however, I do checkout the code before using this action. I have a workflow "A" that declares a job that uses a reusable workflow "B". Reusable workflow "B" has a single job with 2 steps: step 1 is checkout the code; step 2 is use this action. I'm still getting the above error.

```
# workflow A
jobs:
  repo-changes:
    uses: "./.github/workflows/workflow-B.yml"
...
```

```
# workflow B
on:
  workflow_call:
    outputs:
     default_go_dependencies:
        description: "true if the list of default go dependencies have changed"
        value: ${{ jobs.run.outputs.default_go_dependencies }}

jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      default_go_dependencies: ${{ steps.changes.outputs.default-go-dependencies }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/src/github.com/${{ github.repository }}
          fetch-depth: 1

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
...
```
