### ISSUE TITLE
Empty 'Needs' Context 

### ISSUE THREAD

**Issue by moritzkohl1337** [dorny/paths-filter#62]
Hey there!

I'm trying to use this action in a job called 'changes' which runs at the very start of my workflow. It works brilliantly on different steps in the same job but as soon as I try to write an extra job which depends on the 'changes' job using the 'needs' keyword the context object seems to be empty. I've even tried to log the needs object and it seems to be completely empty.

Here is my workflow file. I reckon I've overlooked something but hopefully you will be able to point me to it:

```
name: Build and Provide LPF artifacts

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      project:
        description: 'deploy to project brain-lpf-<dev|tst|prd>'
        required: true
        default: 'brain-lpf-dev'

jobs:
  changes:
    name: Identify Changes
    runs-on: ubuntu-latest
    outputs:
      dataflow-artifacts-dags:
      dataflow-artifacts-tf:
      dataproc-artifacts:
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        name: Identify changes
        id: changes
        with:
          list-files: shell
          filters: |
            dataflow-artifacts-dags:
              - 'cloud-migration/airflow/**'
            dataflow-artifacts-tf:
              - 'cloud-migration/deployment/terraform/**'
            dataproc-artifacts:
              - 'on-premise/src/**'
      - name: Output Changes to DAG Files
        if: ${{ steps.changes.outputs.dataflow-artifacts-dags == 'true' }}
        run: echo ${{ steps.identify-changes.outputs.dataflow-artifacts-dags_files }}
      - name: Output Changes to TF Files
        if: ${{ steps.changes.outputs.dataflow-artifacts-tf == 'true' }}
        run: echo ${{ steps.identify-changes.outputs.dataflow-artifacts-tf_files }}
      - name: Output Changes to Dataproc Jobs Source Files
        if: ${{ steps.changes.outputs.dataproc-artifacts == 'true' }}
        run: echo ${{ steps.identify-changes.outputs.dataproc-artifacts_files }}


  upload-dataflow-artifacts:
    name: Upload Dataflow Artifacts
    runs-on: ubuntu-latest
    needs: changes
    env:
      DATAFLOW_ARTIFACTS_DATAFLOW_NAME: lpf-airflow
      DATAFLOW_ARTIFACTS_DATAFLOW_LOCATION: europe-west1
      DATAFLOW_ARTIFACTS_DAG_LOCAL_LOCATION: cloud-migration/airflow
      DATAFLOW_ARTIFACTS_DAG_REMOTE_LOCATION: dag
      DATAFLOW_ARTIFACTS_TF_LOCAL_LOCATION: cloud-migration/deployment/terraform
      DATAFLOW_ARTIFACTS_TF_REMOTE_LOCATION: data/terraform
    steps:
      - uses: actions/checkout@v2
      - name: Setup gcloud / gsutil
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SA_TERRAFORM }}
          project_id: ${{ github.event.inputs.project }}
          export_default_credentials: false
      - name: Identify Dataflow GCS Bucket
        id: identify_airflow_bucket
        run: |-
          bucket_name=$(
              gcloud composer environments describe ${{ env.DATAFLOW_ARTIFACTS_DATAFLOW_NAME }} \
                          --project=${{ github.event.inputs.project }} \
                          --location=${{ env.DATAFLOW_ARTIFACTS_DATAFLOW_LOCATION }} \
                          --format="get(config.dagGcsPrefix)" \
                          | cut -d/ -f 1-3
          )
          echo "Dataflow bucket identified as '$bucket_name'"
          echo ::set-output name=DATAFLOW_ARTIFACTS_BUCKET::$bucket_name
      - name: Upload DAG Files
        if: ${{ needs.changes.outputs.dataflow-artifacts-dags }}
        run: |-
          from=${{ env.DATAFLOW_ARTIFACTS_DAG_LOCAL_LOCATION }}
          to=${{ steps.identify_airflow_bucket.outputs.DATAFLOW_ARTIFACTS_BUCKET }}/${{ env.DATAFLOW_ARTIFACTS_DAG_REMOTE_LOCATION }}
          echo "Uploading DAG Files from '$from' to '$to'"
          gsutil -m cp -r $from $to
      - name: Upload Terraform Files
        if: ${{ needs.changes.outputs.dataflow-artifacts-tf }}
        run: |-
          from=${{ env.DATAFLOW_ARTIFACTS_TF_LOCAL_LOCATION }}
          to=${{ steps.identify_airflow_bucket.outputs.DATAFLOW_ARTIFACTS_BUCKET }}/${{ env.DATAFLOW_ARTIFACTS_TF_REMOTE_LOCATION }}
          echo "Uploading Terraform Files from '$from' to '$to'"
          gsutil -m cp -r $from $to

  upload-dataproc-artifacts:
    name: Build and Upload LPF Dataproc Artifacts
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.dataproc-artifacts == 'true' }}
    env:
      DATAPROC_ARTIFACTS_BUCKET: ${{ github.event.inputs.project }}-dataproc-artifacts
      DATAPROC_ARTIFACTS_BUILD_PATH: on-premise
      MVN_CMD: mvn clean package -DskipIntegrationTests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-jdk8-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-jdk8-
      - name: Setup gcloud / gsutil
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SA_TERRAFORM }}
          project_id: ${{ github.event.inputs.project }}
          export_default_credentials: true
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Dataproc Artifacts
        run: |-
          cd ${{ env.DATAPROC_ARTIFACTS_BUILD_PATH }}
          eval ${{ env.MVN_CMD }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS_FILE: google-key.json
          GOOGLE_APPLICATION_CREDENTIALS_CONTENT: ${{ secrets.SA_TERRAFORM }}
      - name: Extract Branch name for artifact upload
        id: extract_branch
        run: echo "##[set-output name=BRANCH;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Upload Dataproc Artifacts
        run: |-
          from=${{ env.DATAPROC_ARTIFACTS_BUILD_PATH }}/target/productfeed*.jar
          to=gs://${{ env.DATAPROC_ARTIFACTS_BUCKET }}/${{ steps.extract_branch.outputs.BRANCH }}
          echo "Uploading Dataproc Artifacts from '$from' to '$to'"
          gsutil -m cp -r $from $to
```

Thanks!

EDIT:
 - To log the 'needs' context I've used the following piece of code:
```
 <job-id>:
    - name: log context
    - env:
       NEEDS_CONTEXT: ${{ toJSON(needs) }}
    - run: echo $NEEDS_CONTEXT 
```

**Comment by dorny** [comment]
Hey!

Try this:
```yml
jobs:
  changes:
    name: Identify Changes
    runs-on: ubuntu-latest
    outputs:
      dataflow-artifacts-dags: ${{ steps.changes.outputs.dataflow-artifacts-dags }}
      dataflow-artifacts-tf: ${{ steps.changes.outputs.dataflow-artifacts-tf }}
      dataproc-artifacts: ${{ steps.changes.outputs.dataproc-artifacts }}
```
You are defining the outputs but leaving their values empty.
You have to assign them value from output of given step.
Example of this is [here](https://github.com/dorny/paths-filter#conditional-execution), just expand the `Execute job in a workflow only if some file in a subfolder is changed` section.

Second issue is here: `if: ${{ needs.changes.outputs.dataflow-artifacts-dags }}`.
Action output variables are always strings - so here you will have either `'true'` or `'false'`. I'm not exactly sure about this but if workflow expressions are evaluated the same way as in JavaScript, then `'false'` as non-empty string will evaluate as `true`.

Your `if` expression should be `if: ${{ needs.changes.outputs.dataflow-artifacts-dags == 'true' }}`.
Same applies for other places.

Hope, it will work :)
