### ISSUE TITLE
How to handle empty matrix

### ISSUE THREAD

**Issue by sam-hoffman** [dorny/paths-filter#66]
I'd like to run actions with the matrix option only when the matrix isn't empty, but I'm currently getting an error saying "Matrix vector does not contain any values".

Ideally, if the matrix vector didn't contain any values, the test job would not run. 

My action looks like this:
```
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'services' output variable
      services: ${{ steps.filter.outputs.changes }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          service1: 
            - service1/**/*.py
            - service1/env.yml
          service2:
            - service2/**/*.py
            - service2/env.yml

  # JOB to test each of modified services
  test:
    needs: changes
    strategy:
      matrix:
        # Parse JSON array containing names of all filters matching any of changed files
        service: ${{ fromJson(needs.changes.outputs.services) }}
    runs-on: ubuntu-latest
    ...
```

Thanks in advance for your help!

**Comment by dorny** [comment]
You can use `if` condition like this:
```
test:
  needs: changes
  if: ${{ needs.changes.outputs.services != '[]' && needs.changes.outputs.services != '' }}
  strategy:
    matrix:
      service: ${{ fromJson(needs.changes.outputs.services) }}
```

Job `if` condition is evaluated before job is actually started. I think it's evaluated only once and is not affected by matrix strategy although I'm not 100% sure about that.

Both job  and steps outputs are just strings. That's why you have to use `fromJson()` to parse it into array.
Empty array will be serialized as `[]` so you can simply check it in the `if` condition.
Second part of the condition just checks if it's not an empty string - that would mean some failure during `changes` job execution.

**Comment by sam-hoffman** [comment]
This worked great! Thank you so much, and thanks for this great action :)

**Comment by sshymko** [comment]
To account for empty array formatting differences (`[]`, `[ ]`, etc.), the condition can be updated like so:
```yaml
test:
  needs: changes
  if: ${{ needs.changes.outputs.services != '' && toJson(fromJson(needs.changes.outputs.services)) != '[]' }}
```
