### ISSUE TITLE
Picking up extra files during workflow dispatch.

### ISSUE THREAD

**Issue by sauln** [dorny/paths-filter#71]
When I merge a PR, the filters work correctly, but when I run the same thing from a workflow_dispatch trigger, this action views all files as `added`. From the logs, I see `No merge base found - all files will be listed as added` when the base is correctly resolved as `main`.  This happens even when the number of commits in the PR is small, so I don't think increasing `depth` would fix this.

Here's the relevant snippet from my action:
```     
     - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            settings:
              - 'es_settings/**'

     - name: "Trigger bootstrap"
        if: steps.changes.outputs.settings == 'true'
        id: bootstrap
        uses: ./.github/actions/bootstrap
```

When run as workflow_dispatch, all files in `es_settings` directory are flagged as added even though none of these files changed.
```
Matching files:
  es_settings/<filename>.json [added]
  ...
  es_settings/<other filename>.json [added]
```

Here's the run logs during `workflow_dispatch`:
```
Changes will be detected against the branch main
Checking if commit for main is locally available
  /usr/bin/git cat-file -e main^{commit}
  fatal: Not a valid object name main^{commit}
Fetching main
  /usr/bin/git fetch --depth=10 --no-tags origin main:main
  From https://github.com/<repo name>
   * [new branch]      main       -> main
   * [new branch]      main       -> origin/main
Searching for merge-base with main
  /usr/bin/git merge-base main HEAD
  /usr/bin/git rev-list --count HEAD
  1
  /usr/bin/git rev-list --count main
  46
  /usr/bin/git fetch --deepen=10 --no-tags
  From https://github.com/<repo name>
   * [new branch]      <branch name> -> origin/<branch name>
  /usr/bin/git rev-list --count HEAD
  25
  /usr/bin/git rev-list --count main
  14
  No merge base found - all files will be listed as added
```

and here's the run logs when running from a merge:
```
Fetching list of changed files for PR#58 from Github API
```

Am I using this wrong during `workflow_dispatch`?  It looks like the `base` of `main` branch is inferred correctly, but no merge base is being correctly set?

**Comment by sauln** [comment]
So I played with a few parameters and got it working. With the extra params `base` and `initial-fetch-depth` set, it seems fine.  I don't really understand why this is, as the defaults for both of these should be sufficient.  The default for base should be set to `main` correctly, and the `initial-fetch-depth: 20` should be plenty for the PRs I was playing with earlier today.  

Any explanation why this fixed it?  Possibly, I don't correctly understand what these parameters are doing, or the defaults are not set correctly?

```
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            settings:
              - 'es_settings/**'
          base: main
          initial-fetch-depth: 50

      - name: "Trigger bootstrap"
        if: steps.changes.outputs.settings == 'true'
        id: bootstrap
        uses: ./.github/actions/bootstrap
```


Here are the logs:
```
Changes will be detected against the branch main
Checking if commit for main is locally available
  /usr/bin/git cat-file -e main^{commit}
  fatal: Not a valid object name main^{commit}
Fetching main
  /usr/bin/git fetch --depth=10 --no-tags origin main:main
  From https://github.com/<repo>
   * [new branch]      main       -> main
   * [new branch]      main       -> origin/main
Searching for merge-base with main
  /usr/bin/git merge-base main HEAD
  /usr/bin/git rev-list --count HEAD
  1
  /usr/bin/git rev-list --count main
  48
  /usr/bin/git fetch --deepen=10 --no-tags
  From https://github.com/<repo>
   * [new branch]      <branch name> ->  origin/<branch name>
   * [new branch]       <other branch name> -> origin/<other branch name>
  /usr/bin/git rev-list --count HEAD
  111
  /usr/bin/git rev-list --count main
  109
  /usr/bin/git merge-base main HEAD
  042db6b32b1646e911888a850029fd6ed919767d
Change detection main...HEAD
  /usr/bin/git diff --no-renames --name-status -z main...HEAD
  M<filename>M<filename>M<filename>M<filename>M<filename>M<filename>M<filename>
Results:
Filter settings = false
  Matching files: none
```
