### ISSUE TITLE
feature request: allow duplicate keys in filter

### ISSUE THREAD

**Issue by maurerbot** [dorny/paths-filter#72]
There are some cases where I may want to use the same key for n+1 filters. For instance, if you have a `src/<group>/**` and `deploy/<group>/**` directory where changes in the `<group>` directory in either locations should trigger a build that is named `<group>` which is also the filter key.

```
Run dorny/paths-filter@v2.9.0
Error: duplicated mapping key at line 2, column 1:
    gcf    : 'src/gcf/**'
    ^
```
It would be nice if the outputs was a set array that loaded unique keys from the filter.

**Comment by dorny** [comment]
If I got it right, it's already supported:
```yml
- uses: dorny/paths-filter@v2
  id: changes
  with:
    filters: |
      gcf:
        - 'src/gcf/**'
        - 'deploy/gcf/**'
```

If you mean something else, please post here complete example how the filter declaration and output would look like.
