### ISSUE TITLE
Only files in src

### ISSUE THREAD

**Issue by zRelux** [dorny/paths-filter#86]
Does this action allow me to run only if the files changed are in `src` and nowhere else?

P.S. I am new to github actions...

**Comment by dorny** [comment]
Files can be anywhere, `src` in README was just an example :)

Here is the example from README - what's written with uppercase should be replaced by your custom names and paths:
```
- uses: dorny/paths-filter@v2
  id: changes
  with:
    filters: |
      NAME_OF_YOUR_FILTER:
        - 'SOME_PATH'
        - 'SOME_ANOTHER_PATH'

  # run only if some file in 'src' folder was changed
  if: steps.changes.outputs.NAME_OF_YOUR_FILTER == 'true'
  run: ...
```
