### ISSUE TITLE
Error: This action requires 'base' input to be configured

### ISSUE THREAD

**Issue by sandesha-rao-by** [dorny/paths-filter#87]
I have a requirement where workflow needs to run a job only if a file is changed in a specific folder . So I had used the below snippet in out github action .

```
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        # https://github.com/dorny/paths-filter
        id: should_we_deploy
        with:
          filters: |
            src:
              - 'code/xyz/**'
```

This fails when it runs in the main (For the PRs it works fine) with the error "Error: This action requires 'base' input to be configured or 'repository.default_branch' to be set in the event payload" . However in the repository default branch is set and it is `main` . The logs from the action 

`Run dorny/paths-filter@v2
  with:
    filters: src:
    - ‘code/xyz/**’
    token: ***********
    list-files: none
    initial-fetch-depth: 100
Get current git ref
  /usr/bin/git branch --show-current
  main
Error: This action requires 'base' input to be configured or 'repository.default_branch' to be set in the event payload`

Can this be due to mis configuration ? Thanks
