### ISSUE TITLE
Question: Using list-files to configure matrix

### ISSUE THREAD

**Issue by MitchJans-jstack** [dorny/paths-filter#89]
I have looked at the examples in the readme, but I can't get this to work:

There's a dir called `Deploy` in my project, with each file inside named after an Azure resource I want to deploy something to, and the contents being the version I want to deploy.  Something like
```
./Deploy/ase-something-dev
./Deploy/ase-something-staging
./Deploy/ase-seomthing-prod
```

I want to use paths-filter to conditionally run some steps, including the deployment. As I saw that list-files is possible I am trying to use it to configure a matrix as such:
```yaml
# on, env omitted
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.filter.outputs.deploy }}
      application: ${{ steps.filter.outputs.application }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            deploy:
              - 'Deploy/**'
            application:
              - '!(Deploy/**)'
          list-files: json
  
  # some other jobs omitted
  
  deploy:
    needs: [detect-changes, some-other-step]
    if: # omitted
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        # is it correct to expect the 'deploy_files' output here? And should it be valid json?
        environment: ${{ fromJSON(needs.detect-changes.outputs.deploy_files) }}
    steps:
      # I would expect this to output 'current environment is ./Deploy/ase-something-dev', etc
      - run: echo "current environment is ${{ matrix.environment }}"
```

My workflow is failing at the deploy job with `Error when evaluating 'strategy' for job 'deploy'. (Line: 101, Col: 22): Error reading JToken from JsonReader. Path '', line 0, position 0.,(Line: 101, Col: 22): Unexpected value ''`

**Comment by MitchJans-jstack** [comment]
Figure it out in the mean time: I had to 'export' the output of the filter step to the job using
```yaml
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.filter.outputs.deploy }}
      deploy_files: ${{ steps.filter.outputs.deploy_files }} # <---- This is the line that fixed it
      application: ${{ steps.filter.outputs.application }}
```
