### ISSUE TITLE
Get keys of `with.filters`?

### ISSUE THREAD

**Issue by merlinpatt** [dorny/paths-filter#92]
Assuming I use the example below, is there a way I can dynamically get the keys (`frontend`, `backend`) of `with.filters?

Something like `steps.filters.keys` would output `'[frontend, backend]'`

```
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'
```

**Comment by dorny** [comment]
Keys of filters that evaluated to `"true"` are provided in the `changes` output variable. It uses JSON formatting. This is usually used as an input for matrix jobs.

There is no output variable that would list all the keys, no matter if there were changes or not. But It could be added without much effort. Another solution could be to have filter definition as a standalone YAML file and then use some scripting to get the list of keys.

**Comment by merlinpatt** [comment]
Regarding the yaml file, what does that look like?

I saw how to use the file, but can you provide an example of what `.github/filters.yaml` looks like?

```
- uses: dorny/paths-filter@v2
      id: filter
      with:
        # Path to file where filters are defined
        filters: .github/filters.yaml
```

**Comment by dorny** [comment]
Format of `filters.yaml` (or whatever name you use for the file) is exactly the same as what you can set as `filters` input variable.

Example:
Let's say you have a workflow file like this:
```YAML
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'
```

You could move the filters into separate file:
```yaml
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: .github/filters.yaml
```

Content of `.github/filters.yaml`:
```yaml
backend:
  - 'backend/**'
frontend:
  - 'frontend/**'
````

Github input variables can only be strings. Maybe you noticed the `|` used in the first case.
It basically means all the following lines with more indentation are parsed as one string.
So either you have the filters YAML content loaded from an external file or it is embedded within the workflow file.
Afterwards, it's processed the same way.
