### ISSUE TITLE
Set default output of filter if none are matched?

### ISSUE THREAD

**Issue by merlinpatt** [dorny/paths-filter#93]
I would like to be able to set the default output if the list is empty.

Using the below as an example, I would like to be able to do two things.

1. Set a default like `with.default: [src, server]`
2. Have an option to use all filters as the default if empty. `with.outputAllFilters: true` or something like that

```
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'
```

**Comment by dorny** [comment]
Could you please write more about your use case? I'm trying to understand how this feature would be used.

**Comment by merlinpatt** [comment]
In my codebase, I have jobs that trigger based on an overall set of changed files. For this, I'm using `on.pull_request.paths`.

Within that, I use the filter to see exactly what files changed and determine which tests to run. More specifically, I'm checking if certain locale (country) based files have changed.

But if none of those `filters` match, that means a file was changed that is not locale-specific. Instead the changed file will affect all locales, so all tests should run.

So I'd like to set the output to default to all the keys of `filters`

```
```
name: Snapshot Tests - Non-US
on:
    push:
        branches:
            - develop
            - release
        paths:
            # Generic
            - banners/**
    pull_request:
        paths:
            # Generic
            - banners/**
jobs:
    changedFiles:
        name: Get Changed Locales
        runs-on: ubuntu-latest
        outputs:
            locales: ${{ steps.filter.outputs.changes }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Filter locale paths
              uses: dorny/paths-filter@v2
              id: filter
              with:
                  # DE is first since it takes the longest
                  filters: |
                      DE: '**/DE/**'
                      AU: '**/AU/**'
                      FR: '**/FR/**'
                      GB: '**/GB/**'

            # if none of the filter paths match,
            # another file or multiple files were changed that affect all locales
            - name: Set paths to all locales if none were filtered
              if: steps.filter.outputs.locales == '[]'
              run: # SET LOCALES OUTPUT HERE TO [DE, AU, FR, GB]

    snapshots:
        name: Non-US Snapshots
        runs-on: ubuntu-latest
        needs: changedFiles
        strategy:
            matrix:
                locale: ${{ fromJSON(needs.changedFiles.outputs.locales) }}
                node: [12]
        steps:
            - name: Non-US Snapshot Tests - ${{ matrix.locale }}
              run: |
                  npm run test:func -- --testPathPattern spec/${{ matrix.locale }}
                  ./scripts/snapshot-tests/collect-diffs.sh
```
```

[GitHub Community Post](https://github.community/t/set-default-output-for-a-job/185234)

**Comment by dorny** [comment]
Instead of `with.default: [src, server]`, you could simply have `src` and `server` filters declared as `**`. They would be matched when any file is changed. In other words, they will be always included in `changes` output.

`Have an option to use all filters as the default if empty` - this would be a very specific behavior for your use case.
I have a feeling that `paths-filter` is already quite complex so I would prefer to not extend it with this feature.
But I got an idea of a different solution that could work for you. Otherwise, you can make a fork or process paths-filter output in additional step.

### The possible solution:
Filters already support a list of patterns.
So it could look like this:
```YAML
filters:
  DE:
    - '**/DE/**'
    - COMMON_PATTERN  # matches any file that affects all locales
  AU:
    - '**/AU/**'
    - COMMON_PATTERN  # matches any file that affects all locales
```

So If any of the common files is changed, you will get all locales as changed.
You just need to compose the right `COMMON_PATTERN` pattern to match the files affecting all locales.
With the right directory structure, it should be easy.
If you don't want to change your existing directory structure, you could still compose a complex pattern.
Micromatch supports grouping, "or" logic and negation so it should be possible to express the pattern that matches anything except the files related to some specific locale.

You could also use YAML anchors to define the `COMMON_PATTERN` only once and then just refer to it where you need.
The only downside of using a YAML anchor is that you would get the name of this common filter in the `changes` output which might cause you some troubles. This part could be improved somehow.

What do you think?

**Comment by merlinpatt** [comment]
The common pattern combined with YAML anchors would likely work.

However, there is one more question I have to make sure it would work.

In my common pattern, I would like to include almost all of a top level folder and ignore a specific sublevel folder.

I can do this in `on.push`/`on.pull_request` like below.

Is there a way I can do similarly in the common pattern? Or does micromatch only support inclusion not exclusion?

```
name: Snapshot Tests - Non-US
on:
    push:
        paths:
            # Generic
            - banners/**
            - modals/**
            - server/**
            - src/**
            - tests/functional/spec/*
            - tests/functional/spec/utils/**
            - utils/**
            # Exclude US Files
            - '!banners/US/**'
            - '!modals/US/**'
            - '!server/locale/US/**'
            - '!src/components/modal/content/US*/**'
            - '!tests/functional/spec/US/**'
```

**Comment by Bearbobs** [comment]
> The common pattern combined with YAML anchors would likely work.
> 
> However, there is one more question I have to make sure it would work.
> 
> In my common pattern, I would like to include almost all of a top level folder and ignore a specific sublevel folder.
> 
> I can do this in `on.push`/`on.pull_request` like below.
> 
> Is there a way I can do similarly in the common pattern? Or does micromatch only support inclusion not exclusion?
> 
> ```
> name: Snapshot Tests - Non-US
> on:
>     push:
>         paths:
>             # Generic
>             - banners/**
>             - modals/**
>             - server/**
>             - src/**
>             - tests/functional/spec/*
>             - tests/functional/spec/utils/**
>             - utils/**
>             # Exclude US Files
>             - '!banners/US/**'
>             - '!modals/US/**'
>             - '!server/locale/US/**'
>             - '!src/components/modal/content/US*/**'
>             - '!tests/functional/spec/US/**'
> ```

@merlinpatt  you can use same filters in an inverted approach where you seperate out both path to exculde and include under two filter and use if condition in github workflow to make the decision,like:
```
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      paths-to-exclude: ${{ steps.filter.outputs.paths-to-exclude }}
      paths-to-include: ${{ steps.filter.outputs.paths-to-include }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            paths-to-include:
                - banners/**
                - modals/**
                - server/**
                - src/**
                - tests/functional/spec/*
                - tests/functional/spec/utils/**
                - utils/**
            paths-to-exclude: 
                - 'banners/US/**'
                - 'modals/US/**'
                - 'server/locale/US/**'
  run-tests:
    name: Run tests
    needs: [changes]
    if: ${{ needs.changes.outputs.paths-to-exclude == 'false' && needs.changes.outputs.paths-to-include == 'true' }}
    #actual workflow
```
