### ISSUE TITLE
Ignore pattern ignored? 

### ISSUE THREAD

**Issue by DavidWells** [dorny/paths-filter#97]
I'm trying to check for all backend files that are NOT markdown (`.md`) files and am having some trouble with the patterns.

The following pattern `!src/share/services/**/**.md` picks up the changes to `.github/workflows/ci.yml` (the file this is in).

It seems like this  `!src/share/services/**/**.md` negated pattern will match anything anywhere that's not a markdown file

```yml
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        list-files: 'json'
        filters: |
          backend:
            - 'src/share/services/**'
            - '!src/share/services/**/**.md'
```

Is it possible to do something like this via picomatch?

Thanks for the great action!

**Comment by dorny** [comment]
This should work:
```
filters: |  
  backend:
    - 'src/share/services/**/!(*.md)'
```

Multiple patterns on one filter works like `OR` - it's enough if the file is matched by one pattern.
The `src/share/services/**` pattern already matched your markdown files.

The result of `'!src/share/services/**/**.md'` pattern was not that you excluded markdown files from the `backend` filter. You actually included any file from any path, except the markdown files in the `src/share/services` folders.

**Comment by samuelbeaulieu** [comment]
Hi @dorny, I'm trying to make my action work with a filter, but I really can't seem to make it work.
How can I get everything at the root level except all the content of a specific folder?

I currently have this:
```
# This is a basic workflow to help you get started with Actions

name: Upload themes folder to FTP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  changes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - '**(!themes/**)' <----- THIS IS WHERE I WANT EVERYTHING EXCEPT ALL THE CONTENT FROM /themes
            frontend:
              - 'themes/**'
```

I also tried with:
```
filters: |
            backend:
              - '**'
              - '!themes/**'
```

Can't get it to work. Is it possible to make this case work? Thanks in advance!

**Comment by dorny** [comment]
@samuelbeaulieu 

Sorry for the late response.
In case it's still relevant, this will work:
```yml
filters: |
  backend:
      - '!(themes/**)**'
   frontend:
     - 'themes/**'
```

This action has unit tests for testing the path matching.
If you are not sure, it's best to clone the repo and add a test for your scenario.
It's definitely faster than running the whole CI and trying various solutions.
That's how I do it whenever somebody asks how to write a pattern to match something :)
